// 2026年最新のエンジニアツール動向のデータ
export const categories = {
  ai: "AI & LLM",
  languages: "Languages & Runtimes",
  frameworks: "Frameworks & Libraries",
  databases: "Databases & Backend",
  productivity: "Productivity & Terminals",
  gadgets: "Gadgets & Hardware"
};

// 各カテゴリに属するツール/ガジェットのデータ
export const toolsData = [
  // --- AI & LLM ---
  {
    id: "claude-code",
    name: "Claude Code / 3.7 Sonnet",
    category: "ai",
    trendScore: 99,
    mentions24h: 4210,
    mentions7d: 28500,
    mentions30d: 112000,
    description: "2026年現在、エンジニアの間で圧倒的支持を得るエージェント型AIツール。卓越した論理的推論力とコード修正精度を誇り、単なるコード補完を超えて自律的にデバッグや設計を行います。",
    trendData: [75, 78, 80, 84, 88, 92, 95, 97, 98, 99],
    isAffiliate: false,
    url: "https://www.anthropic.com/claude"
  },
  {
    id: "cursor",
    name: "Cursor",
    category: "ai",
    trendScore: 98,
    mentions24h: 3820,
    mentions7d: 25100,
    mentions30d: 99000,
    description: "AI-firstのコードエディタとして標準の地位を確立。複数ファイルにまたがるコードベースの理解力が高く、チャットとコード修正のシームレスな統合がRedditでも大絶賛されています。",
    trendData: [88, 90, 91, 93, 94, 95, 96, 98, 97, 98],
    isAffiliate: false,
    url: "https://www.cursor.com/"
  },
  {
    id: "deepseek-ollama",
    name: "DeepSeek / Ollama (Local)",
    category: "ai",
    trendScore: 94,
    mentions24h: 3100,
    mentions7d: 21400,
    mentions30d: 84000,
    description: "サブスク型AIツールへの経済的疲労とプライバシー懸念から、ローカルで動くOllamaや、安価で極めて高性能なDeepSeekのAPI連携を選ぶ開発者が急増し、Redditのトレンドを牽引しています。",
    trendData: [45, 55, 68, 75, 82, 85, 89, 92, 93, 94],
    isAffiliate: false,
    url: "https://ollama.com/"
  },
  {
    id: "windsurf",
    name: "Windsurf",
    category: "ai",
    trendScore: 89,
    mentions24h: 1950,
    mentions7d: 14200,
    mentions30d: 59000,
    description: "Cursorの対抗馬として浮上した次世代AI-first IDE。「Flows」と呼ばれる強力なエージェント連携機能が話題を呼び、急速にシェアを伸ばしています。",
    trendData: [30, 42, 50, 60, 68, 75, 80, 83, 86, 89],
    isAffiliate: false,
    url: "https://codeium.com/windsurf"
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    category: "ai",
    trendScore: 88,
    mentions24h: 1800,
    mentions7d: 13900,
    mentions30d: 56000,
    description: "開発環境における定番インラインコード補完ツール。安定性は高いものの、エージェント機能の不足や他の強力な競合ツールへの移行に関する議論が活発化しています。",
    trendData: [92, 91, 90, 89, 88, 88, 89, 88, 89, 88],
    isAffiliate: false,
    url: "https://github.com/features/copilot"
  },

  // --- Languages & Runtimes ---
  {
    id: "python",
    name: "Python",
    category: "languages",
    trendScore: 95,
    mentions24h: 3300,
    mentions7d: 22800,
    mentions30d: 91000,
    description: "AI・機械学習の急成長に加え、バックエンドAPI開発としての需要（FastAPI等）が再燃し、Stack Overflow等の調査でも前年比+7%以上の成長を記録し大復活を遂げています。",
    trendData: [88, 89, 91, 90, 92, 93, 94, 94, 95, 95],
    isAffiliate: false,
    url: "https://www.python.org/"
  },
  {
    id: "typescript",
    name: "TypeScript",
    category: "languages",
    trendScore: 94,
    mentions24h: 3100,
    mentions7d: 21500,
    mentions30d: 89000,
    description: "静的型付けによる堅牢なフロントエンド/バックエンド開発を支える、現代Web開発の不動のデファクトスタンダード。安定した人気を誇ります。",
    trendData: [93, 94, 93, 94, 95, 94, 93, 94, 94, 94],
    isAffiliate: false,
    url: "https://www.typescriptlang.org/"
  },
  {
    id: "rust",
    name: "Rust",
    category: "languages",
    trendScore: 93,
    mentions24h: 2900,
    mentions7d: 20100,
    mentions30d: 83000,
    description: "高いメモリ安全性と極限のパフォーマンス。開発ツールや新ターミナル等の「Rust製ツール」の台頭に伴い、開発者から最も『愛されている（Admired）』言語の座を数年連続で維持しています。",
    trendData: [90, 91, 92, 91, 93, 92, 93, 93, 92, 93],
    isAffiliate: false,
    url: "https://www.rust-lang.org/"
  },
  {
    id: "go",
    name: "Go",
    category: "languages",
    trendScore: 87,
    mentions24h: 1980,
    mentions7d: 14100,
    mentions30d: 59000,
    description: "シンプルな言語仕様、高速なコンパイル、並行処理能力により、クラウドネイティブインフラや大規模サービス用の定番として信頼性を確立しています。",
    trendData: [85, 86, 85, 87, 86, 88, 87, 88, 86, 87],
    isAffiliate: false,
    url: "https://go.dev/"
  },
  {
    id: "gleam",
    name: "Gleam",
    category: "languages",
    trendScore: 74,
    name: "Gleam",
    description: "Erlang VM上で動作する、静的型付けのモダンな関数型言語。極めて高い並行処理能力とクリーンなコード表現で、Reddit等のWeb開発者の間で人気が急上昇しています。",
    trendData: [45, 50, 55, 58, 62, 65, 68, 70, 72, 74],
    isAffiliate: false,
    url: "https://gleam.run/"
  },

  // --- Frameworks & Libraries ---
  {
    id: "react-next",
    name: "React 19 / Next.js 15",
    category: "frameworks",
    trendScore: 92,
    mentions24h: 2900,
    mentions7d: 20200,
    mentions30d: 84000,
    description: "React Compiler（自動メモ化）の実用化やServer Actionsの標準化により、WebUI開発の基盤としての地位をより堅牢なものにしています。",
    trendData: [90, 91, 89, 90, 91, 92, 93, 91, 92, 92],
    isAffiliate: false,
    url: "https://nextjs.org/"
  },
  {
    id: "tailwind-v4",
    name: "Tailwind CSS v4.0",
    category: "frameworks",
    trendScore: 91,
    mentions24h: 2800,
    mentions7d: 19800,
    mentions30d: 81000,
    description: "Rustエンジンによる完全な書き直しにより、ビルド速度が最大10倍向上。CSS内での直接定義が可能になり、初期ビルドの劇的な軽量化と手軽さからフロントエンド界隈で熱狂的な支持を集めています。",
    trendData: [60, 68, 75, 80, 83, 85, 88, 89, 90, 91],
    isAffiliate: false,
    url: "https://tailwindcss.com/"
  },
  {
    id: "astro",
    name: "Astro v5",
    category: "frameworks",
    trendScore: 89,
    mentions24h: 2100,
    mentions7d: 15100,
    mentions30d: 61000,
    description: "新機能「Content Layer」の成熟とServer Actions対応により、静的ブログ生成ツールから、部分的な動的アプリもこなせるハイブリッド開発の定番フレームワークへと昇華しました。",
    trendData: [80, 82, 83, 85, 86, 88, 87, 89, 88, 89],
    isAffiliate: false,
    url: "https://astro.build/"
  },
  {
    id: "fastapi",
    name: "FastAPI",
    category: "frameworks",
    trendScore: 87,
    mentions24h: 1850,
    mentions7d: 12900,
    mentions30d: 53000,
    description: "Python人気と連動し、爆速で動作する型安全なAPIサーバー開発ツールとして大ブレイク。型定義によるSwagger UIの自動生成機能が開発の効率を高めます。",
    trendData: [78, 80, 82, 81, 83, 85, 84, 86, 85, 87],
    isAffiliate: false,
    url: "https://fastapi.tiangolo.com/"
  },

  // --- Databases & Backend ---
  {
    id: "postgresql",
    name: "PostgreSQL",
    category: "databases",
    trendScore: 95,
    mentions24h: 3150,
    mentions7d: 21900,
    mentions30d: 92000,
    description: "圧倒的な信頼性と拡張性。近年はベクトル拡張（pgvector）による生成AIデータの親和性向上もあり、多くのエンジニアが選ぶデータベース第1位を守り続けています。",
    trendData: [94, 93, 94, 95, 94, 95, 96, 94, 95, 95],
    isAffiliate: false,
    url: "https://www.postgresql.org/"
  },
  {
    id: "cloudflare-workers",
    name: "Cloudflare Workers / D1",
    category: "databases",
    trendScore: 91,
    mentions24h: 2600,
    mentions7d: 18100,
    mentions30d: 74000,
    description: "世界中のエッジで動作する超低遅延のサーバーレス実行環境と、SQLiteベースのグローバルデータベース。エコシステムが成熟し、エッジ開発のインフラとして絶大な人気を誇ります。",
    trendData: [82, 84, 85, 87, 88, 89, 90, 91, 90, 91],
    isAffiliate: false,
    url: "https://workers.cloudflare.com/"
  },
  {
    id: "redis-valkey",
    name: "Valkey / Redis",
    category: "databases",
    trendScore: 90,
    mentions24h: 2450,
    mentions7d: 17200,
    mentions30d: 71000,
    description: "AIエージェントの短期記憶（チャット履歴など）のキャッシュ用途でRedis人気が再加熱。また、Redis社のライセンス変更に伴うオープンソースのフォーク「Valkey」への移行も本格化しています。",
    trendData: [70, 75, 78, 82, 85, 88, 87, 89, 88, 90],
    isAffiliate: false,
    url: "https://valkey.io/"
  },
  {
    id: "supabase",
    name: "Supabase",
    category: "databases",
    trendScore: 89,
    mentions24h: 2150,
    mentions7d: 15200,
    mentions30d: 63000,
    description: "PostgreSQLをベースとしたオープンソースのFirebase代替サービス。リアルタイムデータベース、ストレージ、Authが即座に揃い、スタートアップの開発スピードを爆発的に高めます。",
    trendData: [85, 86, 85, 87, 88, 87, 88, 89, 88, 89],
    isAffiliate: false,
    url: "https://supabase.com/"
  },

  // --- Productivity & Terminals ---
  {
    id: "ghostty",
    name: "Ghostty",
    category: "productivity",
    trendScore: 94,
    mentions24h: 3100,
    mentions7d: 21800,
    mentions30d: 87000,
    description: "Zig言語で記述された、GPU加速対応の超高速ターミナルエミュレータ。圧倒的なレンダリング速度、極限の低リテンシー、優れたカスタマイズ性で2025〜2026年にかけて開発者から熱狂的な支持を集めています。",
    trendData: [35, 50, 62, 70, 80, 85, 90, 92, 93, 94],
    isAffiliate: false,
    url: "https://ghostty.org/"
  },
  {
    id: "raycast",
    name: "Raycast",
    category: "productivity",
    trendScore: 90,
    mentions24h: 2100,
    mentions7d: 14800,
    mentions30d: 62000,
    description: "Mac用 Spotlight代替のランチャー。APIによる強力な拡張性や内蔵のAI統合機能が話題となり、作業自動化のためのインフラとして定着しています。",
    trendData: [88, 89, 87, 89, 90, 89, 90, 91, 90, 90],
    isAffiliate: false,
    url: "https://www.raycast.com/"
  },
  {
    id: "zed",
    name: "Zed Editor",
    category: "productivity",
    trendScore: 88,
    mentions24h: 1900,
    mentions7d: 13500,
    mentions30d: 57000,
    description: "Rustで書かれた、圧倒的レスポンスを誇る超軽量コードエディタ。VS Codeの重さに不満を持つ開発者から、驚異的なロード・タイピング速度とマルチプレイ共同編集機能が高く評価されています。",
    trendData: [60, 65, 72, 78, 80, 83, 85, 87, 86, 88],
    isAffiliate: false,
    url: "https://zed.dev/"
  },
  {
    id: "docker-devcontainers",
    name: "Docker / Devcontainers",
    category: "productivity",
    trendScore: 92,
    mentions24h: 2500,
    mentions7d: 17800,
    mentions30d: 73000,
    description: "再現可能な開発環境をコンテナ化してAIに渡したり、複数開発者間で統一する手法（Devcontainers）が広く実用化され、モダン開発の重要なインフラとなっています。",
    trendData: [90, 91, 90, 92, 91, 93, 92, 92, 91, 92],
    isAffiliate: false,
    url: "https://www.docker.com/"
  },

  // --- Gadgets & Hardware (Affiliate) ---
  {
    id: "hhkb-studio",
    name: "HHKB Studio",
    category: "gadgets",
    trendScore: 93,
    mentions24h: 1200,
    mentions7d: 8900,
    mentions30d: 38000,
    description: "キーボードから手を離さずに操作できる「ポインティングスティック」と「ジェスチャーパッド」を搭載した、HHKBの最高峰フラグシップモデル。静音メカニカルスイッチによる極上の打鍵感。",
    trendData: [78, 80, 82, 85, 87, 90, 92, 93, 92, 93],
    isAffiliate: true,
    affiliatePrice: "¥44,000",
    url: "https://amzn.to/example-hhkb-studio",
    imageName: "hhkb_studio.png"
  },
  {
    id: "mx-master-3s",
    name: "Logicool MX Master 3S",
    category: "gadgets",
    trendScore: 90,
    mentions24h: 1050,
    mentions7d: 7800,
    mentions30d: 32000,
    description: "静音クリック、1秒間に1000行スクロール可能なMagSpeed電磁気スクロールホイールを搭載。エルゴノミクスに基づいた究極の快適性を持つ、プロの開発者のための高機能マウス。",
    trendData: [88, 89, 88, 90, 89, 91, 90, 91, 90, 90],
    isAffiliate: true,
    affiliatePrice: "¥16,900",
    url: "https://amzn.to/example-mx-master-3s",
    imageName: "mx_master_3s.png"
  },
  {
    id: "keychron-q1-max",
    name: "Keychron Q1 Max",
    category: "gadgets",
    trendScore: 85,
    mentions24h: 750,
    mentions7d: 5400,
    mentions30d: 23000,
    description: "フルアルミボディ、ガスケットマウント設計による圧倒的に高品質でコトコト心地いい打鍵サウンド。ホットスワップ対応や2.4GHzワイヤレス、QMK/VIAによる自在なキーカスタムが可能な最高峰自作系キーボード。",
    trendData: [75, 78, 79, 81, 83, 84, 86, 85, 84, 85],
    isAffiliate: true,
    affiliatePrice: "¥36,800",
    url: "https://amzn.to/example-keychron-q1",
    imageName: "keychron_q1.png"
  },
  {
    id: "mx-ergo",
    name: "Logicool MX ERGO",
    category: "gadgets",
    trendScore: 82,
    mentions24h: 580,
    mentions7d: 4200,
    mentions30d: 18000,
    description: "傾斜角を0度または20度にカスタマイズ可能。腕や手首への負担を劇的に減らすプレミアム親指操作トラックボール。長時間のコーディングセッションでも圧倒的な疲れにくさを提供。",
    trendData: [80, 81, 80, 82, 81, 83, 82, 83, 81, 82],
    isAffiliate: true,
    affiliatePrice: "¥15,400",
    url: "https://amzn.to/example-mx-ergo",
    imageName: "mx_ergo.png"
  }
];
