// 2026年最新 IT全般網羅トレンドデータ (全18カテゴリ・計500個超)
export const categories = {
  ai_assistants: "AIアシスタント",
  llm_models: "AI・LLMモデル",
  languages: "プログラミング言語",
  runtimes: "ランタイム・コンパイラ",
  frameworks: "Web・アプリフレームワーク",
  libraries: "ライブラリ・UIコンポーネント",
  databases: "データベース",
  backend: "バックエンド・BaaS",
  cloud_devops: "クラウド & DevOps",
  security: "サイバーセキュリティ",
  mobile_dev: "モバイル開発",
  data_ai: "データ & AI基盤",
  iot_embedded: "IoT & 組み込み",
  productivity: "生産性 & 開発環境",
  terminals: "ターミナル & CLI",
  devices: "入力・出力機器",
  gadgets: "オフィス環境 & スマート機器",
  components: "PCパーツ"
};

const tag = "stackhub-22";

// データソースごとの評価重みづけ (Weighted Scoring Model)
export const sourceWeights = {
  googleTrends: 0.30, // 30%: Google 検索統計 (開発者の関心・検索需要)
  github:       0.25, // 25%: GitHub API (コード規模・Star・実用資産)
  hackerNews:   0.20, // 20%: Hacker News API (アーリーアダプター・先進速報性)
  reddit:       0.15, // 15%: Reddit コミュニティ (議論の熱量・口コミ)
  npm:          0.10  // 10%: パッケージ・実動ライブラリ (実環境DL数)
};

// 開発コミュニティのリアルな曜日サイクル (Weekend Dip) と話題の波を再現するデータ生成関数
function generateRealisticTrendData(score, changePercent, length = 10) {
  const baseStep = (changePercent / 100) / (length - 1);
  const today = new Date();
  
  return Array.from({ length }, (_, idx) => {
    // 1. 長期モメンタムに基づくトレンドベース
    const trendFactor = 1 + baseStep * (idx - (length - 1));
    
    // 2. 実際の曜日サイクルの再現 (土日は開発・投稿アクティビティが25%〜35%低下)
    const daysAgo = Math.round((30 / (length - 1)) * (length - 1 - idx));
    const targetDate = new Date(today.getTime() - daysAgo * 24 * 60 * 60 * 1000);
    const dayOfWeek = targetDate.getDay(); // 0: 日曜, 6: 土曜
    
    let weekendFactor = 1.0;
    if (dayOfWeek === 0) weekendFactor = 0.68;      // 日曜日は約32%減少
    else if (dayOfWeek === 6) weekendFactor = 0.78; // 土曜日は約22%減少
    else if (dayOfWeek === 2 || dayOfWeek === 3) weekendFactor = 1.06; // 火・水曜日は週のピーク
    
    // 3. 話題の自然な波（ニュースやリリースによる小さなスパイク）
    const noise = Math.sin(idx * 2.1 + (score % 7)) * 0.05;
    
    const finalScore = Math.round(score * trendFactor * weekendFactor * (1 + noise));
    return Math.max(10, Math.min(99, finalScore));
  });
}

// 500個のデータを効率的に定義・保持するヘルパー関数
function c(id, name, cat, score, changePercent, baseMentions, desc, isAff = false, price = "", url = "", img = "") {
  // 曜日周期と自然波形を持ったリアルな過去30日間トレンド推移を算出
  const trendData = generateRealisticTrendData(score, changePercent, 10);

  // データソース別重み評価の内訳 (Weighted Breakdown)
  const weightedBreakdown = {
    googleTrends: Math.round(score * 0.30),
    github:       Math.round(score * 0.25),
    hackerNews:   Math.round(score * 0.20),
    reddit:       Math.round(score * 0.15),
    npm:          Math.round(score * 0.10)
  };

  return {
    id, name, category: cat, trendScore: score,
    changePercent: changePercent, // 前週比・前期間比の変化率% (+15.2 や -8.4 等)
    weightedBreakdown,           // ソースごとの重みづけ評価内訳
    mentions24h: Math.round(baseMentions / 30),
    mentions7d: Math.round(baseMentions / 4),
    mentions30d: baseMentions,
    description: desc,
    isAffiliate: isAff,
    affiliatePrice: price,
    url: isAff ? url : (url || `https://github.com/${id}`),
    imageName: img,
    trendData
  };
}

export const toolsData = [
  // ==================== AI Assistants (30個) ====================
  c("claude-fable-5", "Claude Fable 5", "ai_assistants", 99, 28.4, 91000, "論理的思考と自律デバッグにおいて圧倒的精度を誇るAnthropicの最新フラッグシップモデル。", false, "", "https://www.anthropic.com/claude"),
  c("cursor", "Cursor", "ai_assistants", 96, 18.2, 98000, "コードベース全体を多次元インデックスし、自律修正を行うAI-first IDEの代表格。", false, "", "https://www.cursor.com/"),
  c("windsurf", "Windsurf", "ai_assistants", 92, 24.5, 59000, "「Flows」機能で複数ファイルのエージェント編集を爆速化させたCursor最大のライバルAI IDE。", false, "", "https://codeium.com/windsurf"),
  c("github-copilot", "GitHub Copilot", "ai_assistants", 82, -2.1, 260000, "エディタ統合型コード補完の草分け。巨大なエンタープライズ導入シェアを誇る。"),
  c("chatgpt-o3", "OpenAI o3-mini", "ai_assistants", 91, 15.8, 84000, "OpenAIの最新高推論モデル。複雑な数学、競技プログラミング、深層デバッグで驚異の性能。"),
  c("gemini-2-pro", "Gemini 2.0 Pro", "ai_assistants", 90, 19.3, 73000, "Googleのフラッグシップ。200万トークン超の超長大コンテキスト窓と爆速マルチモーダル処理が強み。"),
  c("v0-vercel", "v0 by Vercel", "ai_assistants", 89, 14.2, 68000, "UIコンポーネントや完全なWeb UIを対話形式で瞬時に生成・プレビューするフロントエンド特化AI。"),
  c("bolt-new", "bolt.new", "ai_assistants", 87, 22.1, 53000, "ブラウザ上でWebアプリを丸ごと構築・環境構築・デプロイまで自律実行する先進的フルスタック生成AI。"),
  c("openui", "OpenUI", "ai_assistants", 78, 6.4, 27000, "HTMLやReact、SvelteなどのUI要素を即座にコード化して描画・検証するオープンツール。"),
  c("phind", "Phind", "ai_assistants", 76, -1.8, 22000, "開発者に特化したAI検索エンジン。最新の公式ドキュメントを参照した正確な解説が魅力。"),
  c("perplexity-ai", "Perplexity", "ai_assistants", 88, 12.0, 64000, "対話型のリアルタイムWebサーチエンジン。信頼できる参照ソースを明示しつつ要約回答。"),
  c("you-com", "You.com", "ai_assistants", 72, -4.5, 18000, "開発向けのYouCode等を備え、ソースコードや技術論文を優先的に検索・整理するAI。"),
  c("sourcegraph-cody", "Cody by Sourcegraph", "ai_assistants", 78, 3.2, 25000, "大規模リポジトリのコード構造を正確に理解し、コンテキストに沿った回答を行うAIアシスタント。"),
  c("tabnine", "Tabnine", "ai_assistants", 70, -6.1, 38000, "プライベート環境やオンプレミスでも完全に動作する、セキュリティ・プライバシー重視型AI。"),
  c("double-bot", "Double.bot", "ai_assistants", 71, 2.1, 15000, "VS Codeに密結合し、最新の主要モデルを切り替えながら開発できるAI拡張機能。"),
  c("supermaven", "Supermaven", "ai_assistants", 85, 16.7, 41000, "30万トークンの巨大コンテキストと、業界最速レベルの応答速度を誇るコード補完エンジン。"),
  c("bleep-search", "Bleep", "ai_assistants", 74, 5.4, 13000, "自然言語でローカルコードベース全体を検索・解析できる、Rust製のAIローカルツール。"),
  c("blackbox-ai", "Blackbox AI", "ai_assistants", 72, -3.2, 29000, "画面上の動画や画像からコードを抽出し、リアルタイムで補完を行う開発者向けAI。"),
  c("julius-ai", "Julius AI", "ai_assistants", 75, 8.1, 16000, "Pythonコードの自動生成・実行、データ解析や高度なグラフ描画を対話で行うデータAI。"),
  c("replit-agent", "Replit Agent", "ai_assistants", 86, 18.9, 39000, "テキスト指示から環境構築・データベース設定・コーディング・公開まで自律完結するAI。"),
  c("lovable-dev", "Lovable", "ai_assistants", 84, 21.3, 21000, "自然言語の仕様定義から実用的なWebアプリを数分で自動構築する次世代AIプラットフォーム。"),
  c("uizard", "Uizard", "ai_assistants", 74, -1.2, 18000, "手書きのワイヤーフレームやスケッチから、プロ仕様のUIデザインを即座に生成するAI。"),
  c("gamma-app", "Gamma", "ai_assistants", 80, 7.5, 31000, "テキストを入力するだけで、デザイン性の高いスライドやWebドキュメントを自動生成するAI。"),
  c("adobe-firefly", "Adobe Firefly", "ai_assistants", 78, 2.4, 28000, "商用利用可能な画像を安全に生成・編集できるAdobeのクリエイティブ生成AI。"),
  c("canva-ai", "Canva AI", "ai_assistants", 73, 1.1, 33000, "ノンデザイナーでも一瞬で美しいグラフィックやプレゼン資料を作成できるAIデザインツール。"),
  c("suno-ai", "Suno", "ai_assistants", 83, 9.8, 45000, "歌詞やジャンルを指定するだけで、極めて高品質なボーカル楽曲を生成する音楽AI。"),
  c("v0-dev-deploy", "v0.dev", "ai_assistants", 88, 15.0, 62000, "Vercelが提供する、生成したReactコンポーネントを即時にホスティング・共有するサービス。"),
  c("phind-search", "Phind Search", "ai_assistants", 76, -0.8, 21000, "開発者の検索クエリに対し、Webの最新情報と公式ドキュメントをマージして回答するAI。"),
  c("copilot-workspace", "Copilot Workspace", "ai_assistants", 84, 11.2, 38000, "GitHub上のIssueから仕様書作成、コード変更、PR作成までを自律実行する開発環境。"),
  c("cognition-devin", "Devin", "ai_assistants", 88, 14.8, 52000, "世界初の自律型ソフトウェアエンジニアAI。エラー解決からビルドまで完結させる。"),

  // ==================== LLM & Open Models (30個) ====================
  c("deepseek-r1", "DeepSeek-R1", "llm_models", 97, 42.1, 125000, "高推論性能かつ圧倒的ローカル動作用モデルとして世界中を席巻中のオープンAI。"),
  c("mcp-protocol", "Model Context Protocol", "llm_models", 95, 35.8, 64000, "AIエージェントにローカルツールやファイルを接続するための2026年最重要オープン標準。"),
  c("qwen-2-5-coder", "Qwen 2.5 Coder", "llm_models", 88, 19.4, 61000, "ローカルで動作するオープンコードモデルの中で最高峰の精度を誇るアリババのAI。"),
  c("llama-3-3", "Llama 3.3 70B", "llm_models", 85, 8.2, 55000, "Metaが提供するオープンウェイトモデル。多くのファインチューンAIの基盤。"),
  c("ollama-runner", "Ollama", "llm_models", 92, 22.0, 89000, "Mac/Windows/Linuxのローカル環境で大容量モデルを数コマンドで動かせるランタイム。"),
  c("lm-studio", "LM Studio", "llm_models", 82, 9.5, 46000, "GUIでローカルLLMを簡単に検索・ダウンロード・実行できるデスクトップアプリ。"),
  c("anything-llm", "AnythingLLM", "llm_models", 80, 7.1, 37000, "プライベートドキュメントをローカルLLMと連携させてセキュアに構築できるRAGツール。"),
  c("langchain", "LangChain", "llm_models", 78, -4.2, 62000, "LLMを他のツールやエージェントワークフローと接続する開発フレームワーク。"),
  c("llamaindex", "LlamaIndex", "llm_models", 76, -3.1, 49000, "外部文書をベクトル化し、LLMに効率よくコンテキスト注入するRAG開発フレームワーク。"),
  c("crewai", "CrewAI", "llm_models", 83, 12.8, 43000, "複数のAIエージェントに役割を与え、チームとして協力実行させるフレームワーク。"),
  c("autogen", "AutoGen", "llm_models", 75, -5.0, 41000, "Microsoft製のマルチエージェント会話フレームワーク。エージェント間対話を構築可能。"),
  c("huggingface", "Hugging Face", "llm_models", 84, 5.2, 120000, "世界中のオープンソースモデルやデータセットが集う、機械学習界最大のハブ。"),
  c("flowise", "Flowise", "llm_models", 74, -2.1, 22000, "ドラッグ＆ドロップでLLMアプリやRAG、AIエージェントを構築できるノーコードツール。"),
  c("dify", "Dify", "llm_models", 86, 16.4, 58000, "ワークフロー設計、RAG、プロンプト管理を統合した本格AIアプリ運用のためのBaaS。"),
  c("open-interpreter", "Open Interpreter", "llm_models", 80, 4.0, 33000, "自然言語からPCローカル上でコードを生成・直接実行してタスク自動化を行うAI。"),
  c("replicate", "Replicate", "llm_models", 78, 3.1, 38000, "クラウド上でオープンソースモデルをAPI経由で数秒で実行できる開発者サービス。"),
  c("groq", "Groq", "llm_models", 85, 18.2, 65000, "LPU独自半導体により、Llama3などのオープンモデルを驚異のトークン速度で出力。"),
  c("together-ai", "Together AI", "llm_models", 75, 1.8, 29000, "高性能なオープンソースLLMを超高速かつ安価なAPIとして提供するクラウドAI。"),
  c("cohere", "Cohere", "llm_models", 72, -6.0, 26000, "企業向けに特化した多言語対応RAGやセマンティック検索、テキスト生成API。"),
  c("mistral-large", "Mistral Large", "llm_models", 78, 2.8, 31000, "ヨーロッパ発の高性能LLM。卓越した言語処理能力とリーズナブルなAPI価格が支持される。"),
  c("phi-4-model", "Microsoft Phi-4", "llm_models", 82, 11.5, 27000, "Microsoftが公開した小型かつ極めて高知能なオープンモデル。ローカル動作に最適。"),
  c("gemma-2-model", "Google Gemma 2", "llm_models", 80, 6.2, 48000, "Googleが開発した軽量かつ高性能なオープンモデル。高い推論効率を誇る。"),
  c("command-r-plus", "Command R+", "llm_models", 74, -3.8, 19000, "Cohereのビジネス向け大型オープンモデル。多言語RAGやツール使用に特化。"),
  c("openai-whisper", "Whisper", "llm_models", 86, 7.8, 75000, "OpenAIが開発したオープンソースの超高性能音声文字起こし・翻訳モデル。"),
  c("stable-diffusion", "Stable Diffusion", "llm_models", 80, -8.1, 94000, "オープンソース画像生成AIの代名詞。無数のモデルや拡張機能が開発される。"),
  c("flux-1-model", "Flux.1", "llm_models", 90, 21.0, 52000, "Black Forest Labsによる最新オープン画像生成モデル。文字描画と写実性で最高峰。"),
  c("langgraph", "LangGraph", "llm_models", 88, 17.5, 26000, "循環的なグラフ構造を持つ高度なマルチエージェントを構築するためのライブラリ。"),
  c("dspy-framework", "DSPy", "llm_models", 84, 13.2, 18000, "プロンプト調整ではなくアルゴリズムに基づいてLLM動作を自動最適化するフレームワーク。"),
  c("autogpt", "AutoGPT", "llm_models", 65, -12.5, 82000, "ゴールを設定するだけで自らタスクを分解し、自律的に情報検索・開発を行うAI。"),
  c("semantic-kernel", "Semantic Kernel", "llm_models", 73, -1.0, 21000, "Microsoft製のAI統合フレームワーク。C#やPython等のシステムにLLMを組込可能。"),

  // ==================== Programming Languages (30個) ====================
  c("python", "Python", "languages", 94, 8.5, 550000, "AI、機械学習、データサイエンス分野の圧倒的シェアを背景に成長し続ける汎用言語。"),
  c("typescript", "TypeScript", "languages", 93, 6.2, 360000, "JavaScriptに静的型付けをもたらす現代Webフロントエンドのデファクト言語。"),
  c("rust", "Rust", "languages", 92, 14.8, 270000, "メモリ安全、並行処理、最高速度。開発ツールやシステム開発で愛される言語。"),
  c("zig", "Zig", "languages", 86, 26.5, 63000, "C言語の代替を目指すシステム言語。GhosttyやBunの基盤として急伸中。"),
  c("go", "Go", "languages", 78, 3.1, 220000, "Google製。並行処理と高速なビルド、シンプルな仕様でクラウドインフラの定番。"),
  c("javascript", "JavaScript", "languages", 75, -2.5, 650000, "Webを動かす基盤言語。圧倒的な普及規模だが仕様が安定している。"),
  c("csharp", "C#", "languages", 68, -4.0, 330000, ".NETとともに歩む強固な言語。手堅い生産性と進化を両立。"),
  c("java", "Java", "languages", 52, -9.2, 490000, "基幹業務システムや大規模バックエンドの標準。巨大な運用実績を誇る。"),
  c("cpp", "C++", "languages", 58, -6.4, 250000, "ゲームエンジン、ブラウザ、ハードウェア制御など限界の処理速度を求める領域の重鎮。"),
  c("php", "PHP", "languages", 42, -11.0, 270000, "全世界のWebサイトの多くを支えるサーバーサイドスクリプト言語。"),
  c("ruby", "Ruby", "languages", 48, -8.5, 110000, "「開発者の楽しさ」を最優先に設計された、Railsを支えるオブジェクト指向言語。"),
  c("kotlin", "Kotlin", "languages", 65, -1.2, 145000, "Android開発の公式標準であり、Java互換を持つモダンなJVM言語。"),
  c("swift", "Swift", "languages", 63, -3.0, 138000, "Appleデバイス向け開発の標準言語。高度な安全性とシンプルな表現力を持つ。"),
  c("gleam-lang", "Gleam", "languages", 74, 18.0, 35000, "Erlang BEAM上で動く静的型付けの新しい並行処理言語。クリーンな記述が人気。"),
  c("elixir", "Elixir", "languages", 60, -2.0, 62000, "Erlangを基盤に、耐障害性と大規模並行処理に優れた関数型言語。"),
  c("scala", "Scala", "languages", 50, -10.5, 90000, "オブジェクト指向と関数型プログラミングを強力に融合したJVM言語。"),
  c("clojure", "Clojure", "languages", 47, -7.8, 32000, "Lispの近代的な方言。JVM上で動作しイミュータブルデータ構造を主軸とする。"),
  c("haskell", "Haskell", "languages", 45, -9.1, 53000, "非正格な評価と強力な型システムを持つ、純粋関数型言語の古典的標準。"),
  c("ocaml", "OCaml", "languages", 55, 2.4, 28000, "高い型安全性と実用的なパフォーマンスを持つ静的型付け関数型言語。"),
  c("c-lang", "C", "languages", 64, -5.2, 260000, "低レイヤ言語の原点。OSや組み込み領域で永続的な基礎シェアを持つ。"),
  c("r-lang", "R", "languages", 40, -12.0, 125000, "統計解析、データビジュアライゼーション分野で根強い人気を持つ言語。"),
  c("julia", "Julia", "languages", 54, 1.5, 44000, "C言語並みの実行速度と記述性を両立した、数値解析・科学技術計算用言語。"),
  c("perl", "Perl", "languages", 30, -15.0, 92000, "テキスト処理言語の古典。現在はレガシー環境の保守が中心。"),
  c("nim", "Nim", "languages", 56, 3.2, 24000, "Pythonライクな構文からC/C++へトランスパイルされ高速動作するシステム言語。"),
  c("crystal-lang", "Crystal", "languages", 55, 0.8, 11000, "Rubyのような構文とC言語に迫る速度をあわせ持つコンパイル言語。"),
  c("fortran", "Fortran", "languages", 35, -14.0, 34000, "数値計算の先駆者。学術プログラムや物理シミュレーションを支える。"),
  c("cobol", "COBOL", "languages", 28, -16.5, 48000, "事務処理用歴史的言語。銀行や政府機関のメインフレーム保守で今も現役。"),
  c("lua", "Lua", "languages", 68, 4.1, 79000, "高速動作する軽量組み込みスクリプト言語。Neovim拡張等で活躍。"),
  c("fsharp", "F#", "languages", 62, -1.5, 29000, "Microsoftが主導する.NET環境向けの強力な関数型言語。"),
  c("erlang", "Erlang", "languages", 50, -6.0, 31000, "並行処理と高いネットワーク可用性を第一に設計されたアクターモデル言語。"),

  // ==================== Runtimes & Compilers (30個) ====================
  c("fable-5-compiler", "Fable 5", "runtimes", 89, 21.4, 53000, "F# to JSコンパイラ最新版。MSBuild連携改善と軽量JS出力でWeb開発を加速。"),
  c("bun-runtime", "Bun", "runtimes", 84, 11.2, 130000, "Zigで書かれた超高速JavaScript/TypeScriptランタイムおよびバンドラー。"),
  c("deno-runtime", "Deno", "runtimes", 70, -4.5, 83000, "Rust製で標準でTSやJSXをサポートするセキュアなJSランタイム。"),
  c("node-js", "Node.js", "runtimes", 72, -3.2, 340000, "サーバーサイドJSの巨大な元祖エコシステム。膨大なnpm資産を抱える。"),
  c("luau", "Luau", "runtimes", 68, 2.0, 38000, "Robloxが開発した、Luaに静的型付けと最適化を追加した派生スクリプト言語。"),
  c("dart", "Dart", "runtimes", 62, -5.1, 156000, "Flutterを動かす言語。AOTおよびJITコンパイルにより高速なUI描画を実現。"),
  c("graalvm", "GraalVM", "runtimes", 74, 5.8, 21000, "Javaアプリをネイティブバイナリへ事前コンパイル（AOT）し高速起動させるJVM。"),
  c("pypy", "PyPy", "runtimes", 63, -4.0, 14000, "JITコンパイラを搭載し、CPythonよりも大幅な高速動作を実現したPythonランタイム。"),
  c("v8-engine", "V8 Engine", "runtimes", 78, 1.2, 42000, "Google製のJavaScript/WebAssembly実行エンジン。ChromeやNode.jsの心臓部。"),
  c("wasmer", "Wasmer", "runtimes", 76, 4.3, 17000, "あらゆるプラットフォームや言語に組み込んで動作する超軽量Wasmランタイム。"),
  c("wasmtime", "Wasmtime", "runtimes", 82, 10.5, 28000, "Bytecode Allianceによる、堅牢かつ極めて高速なスタンドアロンWasmランタイム。"),
  c("quickjs", "QuickJS", "runtimes", 72, 2.1, 11000, "数メガバイトのメモリで動作する、極小・高速の組み込みJavaScriptエンジン。"),
  c("esbuild-compiler", "Esbuild", "runtimes", 86, 6.4, 75000, "Go言語で開発された、他のバンドラーの数十倍〜数百倍の速度を誇るトランスパイラ。"),
  c("swc-compiler", "SWC", "runtimes", 85, 7.9, 68000, "Rustで開発された超高速JS/TSコンパイラ。Next.js等のビルド基盤に採用。"),
  c("babel-transpiler", "Babel", "runtimes", 60, -11.2, 140000, "最新のJSコードを古いブラウザ対応コードへ変換する歴史的トランスパイラ。"),
  c("tsc-compiler", "tsc", "runtimes", 88, 3.0, 290000, "公式のTypeScriptコンパイラ。型チェックとJavaScriptコード出力を行う基幹ツール。"),
  c("gcc-compiler", "GCC", "runtimes", 65, -7.0, 95000, "GNUのC/C++その他マルチ言語に対応するオープンソースの伝統的コンパイラ。"),
  c("clang-compiler", "Clang", "runtimes", 78, 2.0, 59000, "LLVMベースのモダンなC/C++コンパイラ。明確なエラー表示と速度で高い人気。"),
  c("ghc-compiler", "GHC", "runtimes", 48, -10.0, 12000, "グラスゴー・ハスケル・コンパイラ。Haskellコードを最適化・コンパイルする標準。"),
  c("rustc-compiler", "rustc", "runtimes", 88, 12.1, 185000, "Rustの公式コンパイラ。高度な安全性チェックを行い実行ファイルを生成する。"),
  c("roslyn-compiler", "Roslyn", "runtimes", 70, -2.0, 31000, "C#およびVisual BasicコンパイラをAPIとして提供するMicrosoft製コンパイラ。"),
  c("goby-runtime", "Goby", "runtimes", 50, -8.0, 4000, "Go言語で開発された、マイクロサービス向けのRubyライクな組み込みスクリプト。"),
  c("micropython", "MicroPython", "runtimes", 74, 3.5, 26000, "マイコンボードや組み込みシステム環境向けに最適化されたPythonランタイム。"),
  c("luajit", "LuaJIT", "runtimes", 75, 1.8, 23000, "JITコンパイルにより、C言語に匹敵する速度でLuaコードを実行するエンジン。"),
  c("truffleruby", "TruffleRuby", "runtimes", 55, -6.5, 9000, "GraalVM上で動作し、JITコンパイルによってRubyの処理能力を引き上げるランタイム。"),
  c("deno-deploy", "Deno Deploy", "runtimes", 82, 8.4, 34000, "Deno公式のエッジサーバーレスホスティング。瞬時に世界中にアプリを展開。"),
  c("graal-nodejs", "Graal.js", "runtimes", 58, -5.0, 8000, "GraalVM上で他のJVM言語とシームレスに対話・実行できるJavaScriptエンジン。"),
  c("ironpython", "IronPython", "runtimes", 40, -13.0, 11000, "C#や.NETのクラスライブラリとPythonプログラムを連携させる実装。"),
  c("jruby-runtime", "JRuby", "runtimes", 48, -9.5, 18000, "Java仮想マシン（JVM）上でRubyプログラムを並列スレッドで動作させるランタイム。"),
  c("wasm-micro-runtime", "WAMR", "runtimes", 72, 4.0, 13000, "IoTデバイス向けに特化した超軽量WebAssembly実行環境。"),

  // ==================== Web & App Frameworks (30個) ====================
  c("react-next", "Next.js", "frameworks", 89, 8.1, 500000, "React Compiler標準対応、App Routerとサーバーアクションを内包したReactの決定版。"),
  c("spring-boot", "Spring Boot", "frameworks", 62, -7.5, 290000, "Java開発の業界標準。手堅いDIコンテナ機能とエコシステムを持つ。"),
  c("laravel", "Laravel", "frameworks", 58, -8.2, 230000, "PHPフレームワークの代名詞。圧倒的な開発速度と洗練されたドキュメントが特徴。"),
  c("nuxt-js", "Nuxt.js", "frameworks", 84, 9.4, 98000, "Vue.jsベースのメタフレームワーク。SSR、静的生成、自動ルーティングを内蔵。"),
  c("remix-run", "Remix", "frameworks", 82, 5.0, 74000, "Web標準とHTTPキャッシュを重視したReactメタフレームワーク。"),
  c("astro-framework", "Astro", "frameworks", 89, 18.5, 125000, "コンテンツ指向サイトに特化した超高速フレームワーク。アイランド設計が特徴。"),
  c("solid-start", "SolidStart", "frameworks", 80, 7.8, 22000, "SolidJSベースのメタフレームワーク。最高のSSRパフォーマンスを提供。"),
  c("hono-api", "Hono", "frameworks", 90, 29.1, 115000, "Cloudflare Workers等のエッジ環境で爆速動作する日本発のWebフレームワーク。"),
  c("express-js", "Express", "frameworks", 70, -5.0, 295000, "Node.jsのための無駄のない極めてシンプルな極小Webフレームワーク。"),
  c("nest-js", "NestJS", "frameworks", 75, 1.2, 92000, "TypeScriptで構築され、大規模設計を支援するNode.js用フレームワーク。"),
  c("django", "Django", "frameworks", 60, -6.8, 187000, "Python製フルスタックWebフレームワーク。管理画面やORM一式が揃う。"),
  c("fastapi", "FastAPI", "frameworks", 86, 12.3, 150000, "Python用超高速APIフレームワーク。型安全と自動ドキュメント生成が強み。"),
  c("ruby-on-rails", "Ruby on Rails", "frameworks", 50, -10.1, 125000, "「設定より規約」を提唱したMVCの元祖。MVP開発の定番。"),
  c("flask", "Flask", "frameworks", 54, -7.0, 155000, "Python用の軽量マイクロフレームワーク。シンプルに拡張機能を統合可能。"),
  c("aspnet-core", "ASP.NET Core", "frameworks", 61, -4.2, 158000, "C#で動作する、高性能でクロスプラットフォーム対応のオープンソースWebフレームワーク。"),
  c("actix-web", "actix-web", "frameworks", 72, 3.8, 44000, "Rust製の超高速かつ直感的なWebアプリケーションフレームワーク。"),
  c("axum-rust", "axum", "frameworks", 80, 11.5, 59000, "TokioチームによるRust用Webフレームワーク。非同期処理の連携に長ける。"),
  c("gin-gonic", "Gin", "frameworks", 68, -2.5, 83000, "Go言語用で圧倒的人気を誇る高速で無駄のないHTTP Webフレームワーク。"),
  c("fiber-go", "Fiber", "frameworks", 74, 5.1, 34000, "Express.jsにインスパイアされた、Goで超高速動作する極小Webフレームワーク。"),
  c("echo-go", "Echo", "frameworks", 71, 0.5, 39000, "高いカスタマイズ性と最小限のメモリ割り当てで動作するGo用のHTTP APIルーター。"),
  c("phoenix-elixir", "Phoenix", "frameworks", 76, 4.2, 42000, "Elixirで実装された、圧倒的なWebsocketリアルタイム通信を誇るMVC。"),
  c("play-scala", "Play Framework", "frameworks", 42, -12.4, 28000, "ScalaおよびJava向けのアジャイル開発に適した非同期リアクティブ型Webフレームワーク。"),
  c("ktor-kotlin", "Ktor", "frameworks", 73, 2.5, 21000, "Kotlinの非同期処理を活用し、サーバーとクライアントを組むフレームワーク。"),
  c("vapor-swift", "Vapor", "frameworks", 68, -1.8, 14000, "Swiftで書かれた非同期Webフレームワーク。型安全にAPIを高速開発できる。"),
  c("symfony-php", "Symfony", "frameworks", 48, -9.0, 72000, "PHPでエンタープライズ開発を行うための極めて再利用性の高いモジュール群。"),
  c("yii-php", "Yii", "frameworks", 35, -14.2, 19000, "PHP用の高性能コンポーネントベースフレームワーク。大規模Webに適した設計。"),
  c("codeigniter-php", "CodeIgniter", "frameworks", 40, -11.5, 44000, "学習コストが極端に低くほぼ設定不要で動作する極小PHPフレームワーク。"),
  c("cakephp", "CakePHP", "frameworks", 32, -15.0, 29000, "素早いプロトタイピングを可能にする歴史あるPHPフレームワーク。"),
  c("django-rest-framework", "DRF", "frameworks", 70, -1.0, 78000, "Django上でRESTful APIを実装するための定番ライブラリ。"),
  c("adonis-js", "AdonisJS", "frameworks", 70, 3.0, 18000, "Node.js向けのフルスタックMVCフレームワーク。Laravelに酷似した強力な環境。"),

  // ==================== Libraries & Build Tools (30個) ====================
  c("tailwind-v4", "Tailwind CSS v4", "libraries", 92, 21.0, 240000, "Rust製エンジン刷新でビルド速度10倍となった最新のユーティリティファーストCSS。"),
  c("biome-oxc", "Biome", "libraries", 91, 28.5, 92000, "ESLintとPrettierを統合し、爆速静的解析を実現したRust製モダンツールチェーン。"),
  c("rspack", "Rspack", "libraries", 87, 19.2, 61000, "Webpack完全互換のRust製超高速バンドラー。巨大ビルドを秒速化。"),
  c("vite-bundler", "Vite", "libraries", 88, 7.8, 326000, "ノーバンドルによる瞬時の開発サーバー起動を可能にするフロントエンド標準ビルドツール。"),
  c("playwright", "Playwright", "libraries", 89, 14.1, 202000, "Microsoft製。モダンWebアプリを完璧にシミュレートテストする爆速E2Eライブラリ。"),
  c("vitest", "Vitest", "libraries", 85, 11.0, 122000, "Viteベースのプロジェクトに最適化された超高速な単体テスト実行フレームワーク。"),
  c("react-core", "React", "libraries", 90, 2.5, 480000, "コンポーネントベースUI設計を普及させた、最もユーザーの多いMeta製JSライブラリ。"),
  c("vue-core", "Vue", "libraries", 78, -3.1, 210000, "リアクティブ設計と使いやすさを両立した人気のUIライブラリ。"),
  c("svelte-core", "Svelte", "libraries", 84, 8.9, 82000, "仮想DOMを使用せず、ビルド時にコードをJSにコンパイルする軽量UIフレームワーク。"),
  c("angular-core", "Angular", "libraries", 66, -6.5, 180000, "Google製フルスタックWebプラットフォーム。企業の厳密なアプリケーション向け。"),
  c("solid-core", "SolidJS", "libraries", 79, 5.4, 43000, "仮想DOMなしで純粋なDOM更新を高パフォーマンスで行うUIライブラリ。"),
  c("webpack-bundler", "Webpack", "libraries", 55, -12.0, 270000, "リソースの依存関係を整理してバンドルする歴史ある業界標準。"),
  c("jest-testing", "Jest", "libraries", 72, -4.8, 230000, "設定不要ですぐに動く、Meta製の定番JavaScriptテスティングフレームワーク。"),
  c("cypress-testing", "Cypress", "libraries", 68, -7.2, 89000, "ブラウザ上でのユーザー操作をビジュアルにエミュレートテストできる高機能ツール。"),
  c("react-native-lib", "React Native", "libraries", 72, -2.0, 160000, "ReactのロジックでiOS/Androidのネイティブアプリを記述するライブラリ。"),
  c("flutter-lib", "Flutter", "libraries", 80, 3.2, 240000, "Dartを用いて複数プラットフォームのUIを単一コードで描画するツールキット。"),
  c("electron-lib", "Electron", "libraries", 54, -11.0, 110000, "Web技術を用いてマルチプラットフォーム対応デスクトップアプリを構築するフレームワーク。"),
  c("tauri-lib", "Tauri", "libraries", 88, 16.5, 59000, "Rust製。Electronに比べメモリ使用量とファイルサイズを激減させたデスクトップフレーム。"),
  c("capacitor-lib", "Capacitor", "libraries", 70, 0.5, 28000, "WebプロジェクトをiOS/Androidアプリとしてビルド・公開するハイブリッドフレーム。"),
  c("redux-toolkit", "Redux Toolkit", "libraries", 64, -8.0, 150000, "Reactアプリのステートを予測可能にする、Reduxを簡潔に記述するための公式ツール。"),
  c("zustand-state", "Zustand", "libraries", 89, 15.0, 78000, "フックをベースにした、ボイラープレート不要のシンプルで強力なステート管理。"),
  c("recoil-state", "Recoil", "libraries", 50, -14.0, 22000, "Meta製。Reactのコンポーネントツリーに結合できる分散型ステート管理。"),
  c("jotai-state", "Jotai", "libraries", 82, 8.1, 39000, "アトム単位で細かく状態を定義し、再レンダリングを最適化するステート管理。"),
  c("react-query", "TanStack Query", "libraries", 90, 13.4, 110000, "非同期データのフェッチ、キャッシュ、同期、更新をフック一発で解決するツール。"),
  c("lodash", "Lodash", "libraries", 58, -9.0, 390000, "配列やオブジェクトの操作、ユーティリティ関数を網羅した歴史あるライブラリ。"),
  c("axios", "Axios", "libraries", 74, -3.0, 320000, "ブラウザとNode.jsの両方で動作するPromiseベースのHTTPクライアント。"),
  c("zod-schema", "Zod", "libraries", 91, 19.8, 180000, "TypeScriptファーストなスキーマ定義と実行時バリデーションを行うデファクトツール。"),
  c("valibot", "Valibot", "libraries", 84, 17.2, 25000, "モジュラー設計により最終ファイルサイズを9割カットできる超軽量バリデーター。"),
  c("rxjs-reactive", "RxJS", "libraries", 58, -10.0, 120000, "非同期イベントストリームをオブザーバブルパターンで処理するプログラミングライブラリ。"),
  c("threejs-3d", "Three.js", "libraries", 82, 6.0, 62000, "WebGLをラップし、ブラウザ上で3Dグラフィックをレンダリングする決定版。"),

  // ==================== Databases (30個) ====================
  c("postgresql", "PostgreSQL", "databases", 94, 9.8, 430000, "pgvectorでのベクトル検索対応など、最先端AIデータ基盤としても強大なシェアを持つRDB。"),
  c("valkey", "Valkey", "databases", 92, 31.0, 120000, "Redisの代替となるLinux Foundation主導のオープンソースフォーク。移行が加速。"),
  c("mysql", "MySQL", "databases", 65, -6.0, 460000, "世界のWebシステムが採用する最大級のオープンソースRDB。絶対的実績を誇る。"),
  c("oracle-db", "Oracle DB", "databases", 38, -15.0, 270000, "大企業・金融機関の基幹インフラを支える最高峰の商用データベース。"),
  c("duckdb", "DuckDB", "databases", 87, 21.5, 51000, "データ分析、AIモデルのローカルデータ処理用として絶大な人気を得ているインメモリ分析DB。"),
  c("redis-db", "Redis", "databases", 80, -4.2, 273000, "インメモリKVS。一時キャッシュやAIエージェントのログ用途で強固な人気。"),
  c("mongodb", "MongoDB", "databases", 68, -5.1, 241000, "ドキュメント志向NoSQLの代名詞。JSON形式による柔軟なデータ書き込みが強み。"),
  c("sqlite", "SQLite", "databases", 78, 4.0, 223000, "設定不要で動く超軽量ファイル型DB。モバイル内蔵や小規模サービスで強力。"),
  c("mariadb", "MariaDB", "databases", 60, -7.8, 122000, "MySQLから派生した完全OSSのリレーショナルデータベース。コミュニティ維持。"),
  c("dynamodb", "DynamoDB", "databases", 72, -1.0, 137000, "AWSが提供する完全マネージドNoSQL。低レイテンシーと高スケールが特長。"),
  c("clickhouse", "ClickHouse", "databases", 82, 11.2, 62000, "億単位のログデータをミリ秒で解析する列指向の超高速オープンソース分析DB。"),
  c("neo4j", "Neo4j", "databases", 61, -3.5, 32000, "複雑なリレーションデータやソーシャルグラフを高速探索するグラフ型DBの第一人者。"),
  c("cassandra", "Cassandra", "databases", 50, -11.0, 86000, "単一障害点のない超並列分散NoSQL。凄まじい書き込みトラフィックを捌く。"),
  c("elasticsearch", "Elasticsearch", "databases", 74, -2.8, 223000, "テキスト検索、ログ解析に強固な実績を持つ分散型検索・分析エンジン。"),
  c("opensearch", "OpenSearch", "databases", 72, 1.5, 92000, "ElasticsearchのフォークとしてAWS等が主導する完全なオープンソース検索エンジン。"),
  c("sql-server", "SQL Server", "databases", 55, -9.0, 140000, "Microsoftが提供する信頼性の高いRDB。優れた開発ツールとサポート。"),
  c("couchdb", "CouchDB", "databases", 40, -14.0, 11000, "JSONドキュメントを保存しMapReduceで検索可能なフォールトトレラントNoSQL。"),
  c("arangodb", "ArangoDB", "databases", 62, -2.0, 9000, "キーバリュー、ドキュメント、グラフを単一クエリで操作できるマルチモデルDB。"),
  c("scylladb", "ScyllaDB", "databases", 73, 5.0, 13000, "C++で再実装され、Cassandraに比べハード性能を極限まで引き出す高速NoSQL。"),
  c("tidb", "TiDB", "databases", 78, 8.4, 22000, "水平スケーラビリティとMySQL互換、ACIDトランザクションを実現するハイブリッドHTAP。"),
  c("keydb", "KeyDB", "databases", 68, -1.5, 8000, "Redisのマルチスレッド高速フォーク。単一ノードで数倍のスループットを実現。"),
  c("influxdb", "InfluxDB", "databases", 58, -8.1, 65000, "IoTのセンサーデータやメトリクス計測に適した時系列（Time Series）DB。"),
  c("timescaledb", "TimescaleDB", "databases", 62, -3.0, 49000, "PostgreSQL上で時系列データを効率よく扱うための拡張リレーショナルDB。"),
  c("milvus", "Milvus", "databases", 81, 13.8, 43000, "AIの膨大な埋め込みベクトルデータを超高速に比較探索するベクターDB。"),
  c("qdrant", "Qdrant", "databases", 83, 16.5, 46000, "Rust製で極めて高速に動作する、AIセマンティック検索用のベクター検索エンジン。"),
  c("chromadb", "Chroma", "databases", 82, 14.0, 59000, "Python用LLMアプリから数行で立ち上げて動かせる最も軽量な組み込み型ベクターDB。"),
  c("weaviate", "Weaviate", "databases", 84, 12.1, 38000, "GraphQLベースでJSONデータとベクトル検索を統合するオープンソースベクターDB。"),
  c("pinecone", "Pinecone", "databases", 86, 10.2, 72000, "完全マネージドのSaaS型ベクターDB。インフラ管理不要でミリ秒検索を提供。"),
  c("foundationdb", "FoundationDB", "databases", 70, 0.2, 15000, "Appleが主導する、分散ACIDトランザクションを担保した極めて頑丈なKVS。"),
  c("rocksdb", "RocksDB", "databases", 78, 3.0, 33000, "Meta製。フラッシュストレージに最適化され、他DBの組み込みエンジンとして利用。"),

  // ==================== Backend & BaaS (30個) ====================
  c("cloudflare-workers", "Cloudflare Workers", "backend", 91, 17.5, 240000, "世界200拠点以上のエッジで即時にサーバーレスプログラムを起動できる高速プラットフォーム。"),
  c("supabase", "Supabase", "backend", 88, 12.8, 200000, "PostgreSQLを根幹に据え、即時に認証・ストレージ・APIを自動生成するBaaS代表格。"),
  c("turso", "Turso", "backend", 88, 24.1, 53000, "libsqlベース。多数のSQLiteデータベースを瞬時に複製・エッジ展開できるサーバーレスDB。"),
  c("prisma-orm", "Prisma", "backend", 84, 2.5, 125000, "Node.js/TS向け次世代型安全ORM。自動でTSの型定義を構築する。"),
  c("drizzle-orm", "Drizzle ORM", "backend", 87, 21.0, 74000, "TypeScript特化の超軽量でSQLライクなORM。Prismaより遥かに高速。"),
  c("firebase-firestore", "Firestore", "backend", 70, -4.8, 184000, "Firebase用のドキュメントNoSQL BaaS。クライアントから直結できるリアルタイム同期。"),
  c("pocketbase", "PocketBase", "backend", 84, 14.2, 21000, "単一のGo製バイナリで動作する極小BaaS。リアルタイムDB、認証を内蔵。"),
  c("appwrite", "Appwrite", "backend", 78, 4.0, 25000, "Dockerで簡単に自己ホストできるオープンソースのBaaS。"),
  c("nhost-backend", "Nhost", "backend", 72, -1.0, 8000, "PostgreSQL、Hasura、認証、ストレージをセットにしたサーバーレスGraphQL基盤。"),
  c("hasura-graphql", "Hasura", "backend", 79, 3.2, 39000, "データベースから即座に型安全で高速なリアルタイムGraphQL APIを自動構築するエンジン。"),
  c("grafbase", "Grafbase", "backend", 74, -2.5, 9000, "複数のAPIやDBを1つのエンドポイントに統合するエッジGraphQLゲートウェイ。"),
  c("convex-backend", "Convex", "backend", 82, 11.0, 16000, "Reactに完全対応したリアルタイムステートバックエンド。複雑な同期処理を排除。"),
  c("aws-amplify", "AWS Amplify", "backend", 65, -8.0, 59000, "AWSリソースと結合したモバイル・Webアプリ開発向けの迅速なフルスタックBaaS。"),
  c("vercel-serverless", "Vercel Serverless", "backend", 88, 9.5, 98000, "GitプッシュでAPIを即座にエッジ展開するサーバーレスホスティング。"),
  c("netlify-functions", "Netlify Functions", "backend", 68, -6.1, 45000, "Gitコミットと同時に自動でサーバーレスAPIを起動するホスティング環境。"),
  c("edgedb", "EdgeDB", "backend", 80, 8.0, 18000, "PostgreSQLをエンジンに持ち、グラフ構造クエリを搭載した次世代RDB。"),
  c("typeorm", "TypeORM", "backend", 60, -11.0, 92000, "TypeScript/JS環境で長年実績を持つORM。"),
  c("sequelize", "Sequelize", "backend", 58, -12.5, 88000, "Node.js向けの歴史ある定番オブジェクトリレーショナルマッパー。"),
  c("mongoose", "Mongoose", "backend", 70, -3.4, 110000, "MongoDB用のスキーマベースモデリングライブラリ。"),
  c("knex-js", "Knex.js", "backend", 64, -7.0, 5300, "SQLクエリビルダーの定番。JS/TSから安全なクエリを発行する。"),
  c("hibernate-orm", "Hibernate", "backend", 48, -14.0, 88000, "Javaエンタープライズ開発で不動の地位を持つ最高峰のORM。"),
  c("entity-framework", "Entity Framework", "backend", 62, -5.5, 79000, ".NET公式ORM。C#のLINQを用いて型安全にRDBをクエリできる。"),
  c("spring-data", "Spring Data", "backend", 58, -8.0, 71000, "Spring Boot環境でDB操作のボイラープレートコードを排する抽象化機構。"),
  c("tortoise-orm", "Tortoise ORM", "backend", 68, 2.0, 12000, "FastAPI等の非同期環境向けに開発されたDjangoライクなPython用ORM。"),
  c("sqlalchemy", "SQLAlchemy", "backend", 75, 1.8, 96000, "Pythonプログラミング用の最高峰SQLツールキットと強力なORM。"),
  c("diesel-rust", "Diesel", "backend", 76, 4.0, 21000, "コンパイル時にすべてのSQLエラーと不一致を型チェックするRust用静的型安全ORM。"),
  c("sqlx-rust", "SQLx", "backend", 84, 13.5, 38000, "生のSQLを記述しつつコンパイル時にDBスキーマの検証を実行するRust用クエリ。"),
  c("gorm-go", "GORM", "backend", 78, 3.0, 48000, "Go言語用で最も親しまれているORM。テーブルの自動ロードやマイグレーション。"),
  c("planetscale-db", "PlanetScale", "backend", 70, -6.0, 62000, "MySQL（Vitess）を基盤にスキーマ変更のブランチ機能を提供するプラットフォーム。"),
  c("surrealdb-baas", "SurrealDB Cloud", "backend", 78, 6.2, 31000, "SurrealDBを管理不要でエッジ上に展開できる次世代マルチモデルクラウド。"),

  // ==================== Cloud & DevOps (30個) ====================
  c("kubernetes", "Kubernetes", "cloud_devops", 91, 5.2, 380000, "コンテナオーケストレーションの絶対的デファクト標準。大規模運用の要。"),
  c("docker-engine", "Docker", "cloud_devops", 95, 4.1, 620000, "コンテナ仮想化技術の世界的インフラ。開発環境から本番デプロイまでを支配。"),
  c("terraform", "Terraform", "cloud_devops", 88, 3.4, 210000, "Infrastructure as Code (IaC) の最高峰ツール。マルチクラウド定義を標準化。"),
  c("pulumi", "Pulumi", "cloud_devops", 82, 14.8, 48000, "TypeScriptやPython等の慣れ親しんだプログラミング言語でインフラ定義を行うIaC。"),
  c("opentofu", "OpenTofu", "cloud_devops", 86, 22.0, 39000, "Linux Foundation主導のTerraform完全にオープンな代替フォーク。移行が進む。"),
  c("argocd", "Argo CD", "cloud_devops", 89, 12.5, 88000, "Kubernetes特化のGitOps持続的デプロイメント（CD）の標準ツール。"),
  c("helm-k8s", "Helm", "cloud_devops", 78, -1.2, 140000, "Kubernetesパッケージマネージャー。複雑なアプリのマニフェストを簡単管理。"),
  c("ansible", "Ansible", "cloud_devops", 68, -7.5, 190000, "Red Hat製。エージェントレスでサーバー構成管理を自動化するツール。"),
  c("datadog", "DataDog", "cloud_devops", 85, 6.0, 220000, "クラウドインフラ、アプリケーション、ログの監視・可視化を行うSaaSプラットフォーム。"),
  c("prometheus", "Prometheus", "cloud_devops", 82, 1.8, 160000, "時系列メトリクス収集とアラート設定を行うオープンソース監視標準。"),
  c("grafana", "Grafana", "cloud_devops", 86, 4.5, 250000, "あらゆるデータソースを美しいインタラクティブダッシュボードに可視化するツール。"),
  c("github-actions", "GitHub Actions", "cloud_devops", 94, 11.2, 480000, "GitHubと密結合したCI/CD自動化ワークフロー。デファクト標準の地位を確立。"),
  c("gitlab-ci", "GitLab CI/CD", "cloud_devops", 75, -4.0, 210000, "GitLabに組み込まれた強力な継続的インテグレーション・デプロイ機構。"),
  c("circleci", "CircleCI", "cloud_devops", 62, -11.0, 130000, "高速なビルドと柔軟なキャッシュを持つ定番CI/CDクラウドサービス。"),
  c("jenkins", "Jenkins", "cloud_devops", 50, -15.2, 310000, "CI/CDの先駆者。無数のプラグインと歴史的実績を持つセルフホスト自動化サーバー。"),
  c("vault-hashicorp", "HashiCorp Vault", "cloud_devops", 80, 2.1, 78000, "APIキーや暗号化キー、証明書などの機密情報を安全に一元管理するツール。"),
  c("crossplane", "Crossplane", "cloud_devops", 81, 16.0, 29000, "KubernetesのAPIを用いてあらゆるクラウドインフラをコントロールする制御プレーン。"),
  c("k3s-rancher", "K3s", "cloud_devops", 83, 9.8, 41000, "エッジ環境やローカル検証に最適な超軽量Kubernetesディストリビューション。"),
  c("podman", "Podman", "cloud_devops", 80, 8.2, 62000, "デーモンレスかつルート権限不要で動作するDocker完全互換のコンテナエンジン。"),
  c("portainer", "Portainer", "cloud_devops", 76, 5.0, 51000, "DockerやKubernetes環境をWeb UIから簡単に視覚的管理できるツール。"),
  c("cloudflare-tunnel", "Cloudflare Tunnel", "cloud_devops", 90, 19.5, 89000, "パブリックIPやポート開放なしでローカルWebサービスを安全に公開できるネットワークツール。"),
  c("tailscale", "Tailscale", "cloud_devops", 92, 21.4, 95000, "WireGuardを基盤とし、ゼロ設定で安全なメッシュVPNを構築するネットワークサービス。"),
  c("netmaker", "Netmaker", "cloud_devops", 74, 6.1, 14000, "クラウド環境間で超高速なWireGuard仮想ネットワークを自作構築するツール。"),
  c("aws-cdk", "AWS CDK", "cloud_devops", 84, 7.8, 110000, "TypeScriptやPython等のプログラミング言語でAWSインフラをコード定義する開発キット。"),
  c("nix-os", "NixOS / Nix", "cloud_devops", 88, 23.5, 72000, "完全宣言的かつ再現可能なパッケージ管理とOS構築を実現する、パワーユーザーに大人気のLinux。"),
  c("envoy-proxy", "Envoy", "cloud_devops", 78, 1.0, 68000, "クラウドネイティブ環境用に設計された高性能L7プロキシおよびサービスメッシュ基盤。"),
  c("istio-mesh", "Istio", "cloud_devops", 76, -2.1, 91000, "Kubernetes上のマイクロサービス間の通信・認証・監視を束ねるサービスメッシュ。"),
  c("traefik-proxy", "Traefik", "cloud_devops", 81, 4.0, 84000, "Dockerやk8sと自動連動してルーターやSSL証明書を即座に構成するモダンHTTP逆プロキシ。"),
  c("flux-cd", "Flux CD", "cloud_devops", 79, 3.2, 45000, "KubernetesクラスタをGitリポジトリの状態と自動同期させるGitOpsツール。"),
  c("backstage-spotify", "Backstage", "cloud_devops", 82, 11.0, 36000, "Spotifyが開発した、社内の全サービスや開発ドキュメントを一元管理する開発者ポータル基盤。"),

  // ==================== Cybersecurity (30個) ====================
  c("snyk-security", "Snyk", "security", 88, 11.5, 120000, "コード、依存関係、コンテナ、IaCの脆弱性を開発ワークフロー内で自動検知・修正するツール。"),
  c("trivy-aquasec", "Trivy", "security", 90, 16.8, 65000, "コンテナイメージ、ファイルシステム、Gitリポジトリの脆弱性を爆速スキャンするOSSツール。"),
  c("sonarqube", "SonarQube", "security", 78, -1.8, 140000, "コードの静的解析を行い、バグ、脆弱性、セキュリティホールを視覚化する品質検査ツール。"),
  c("semgrep", "Semgrep", "security", 87, 18.2, 41000, "軽量で独自の検索ルールを簡単に記述できる高精度のコード脆弱性・静的解析SASTツール。"),
  c("burp-suite", "Burp Suite", "security", 84, 4.0, 95000, "Webアプリケーションのペネトレーションテスト（診断）における世界標準の診断プロキシ。"),
  c("owasp-zap", "OWASP ZAP", "security", 76, -2.5, 68000, "完全オープンソースで提供されるWeb脆弱性自動スキャナー。CI/CDへの組み込みも容易。"),
  c("kali-linux", "Kali Linux", "security", 82, 2.1, 180000, "数百のセキュリティ検証・ペネトレーションテスト用ツールがプリインストールされたOS。"),
  c("wireshark", "Wireshark", "security", 80, -1.0, 240000, "ネットワークパケットをディープにキャプチャ・解析する世界的標準パケットアナライザー。"),
  c("crowdstrike", "CrowdStrike Falcon", "security", 75, -8.0, 110000, "AIを活用したEDRおよびクラウドセキュリティで企業端末を防護するソリューション。"),
  c("wiz-security", "Wiz", "security", 89, 21.0, 52000, "エージェントレスで多次元のクラウドインフラ脆弱性と設定ミスを分析するセキュリティSaaS。"),
  c("tailscale-ssh", "Tailscale SSH", "security", 91, 19.4, 43000, "鍵管理を排除し、IdentityベースでSSHアクセスコントロールを自動化するセキュリティ機能。"),
  c("teleport", "Teleport", "security", 83, 10.5, 28000, "SSH、Kubernetes、データベースへのゼロトラストアクセスを提供するアクセスゲートウェイ。"),
  c("bitwarden-oss", "Bitwarden", "security", 90, 14.0, 160000, "オープンソースで自己ホストも可能な信頼の個人・チーム向け暗号化パスワードマネージャー。"),
  c("keepassxc", "KeePassXC", "security", 82, 3.5, 78000, "クラウドに依存せず、ローカル暗号化データベースで秘密鍵やパスワードを厳重管理するツール。"),
  c("step-ca", "Smallstep step-ca", "security", 78, 6.2, 19000, "プライベートなDevOps環境向けに証明書（X.509 / SSH）を自動発行・管理するオープンCA。"),
  c("infisical", "Infisical", "security", 86, 22.5, 24000, "チーム内での環境変数（.env）やシークレットをエンドツーエンド暗号化で安全共有・同期するツール。"),
  c("doppler-secrets", "Doppler", "security", 84, 12.0, 31000, "あらゆる開発環境やマルチクラウドへシークレット変数を安全に供給・集中管理するSaaS。"),
  c("gitleaks", "Gitleaks", "security", 87, 15.1, 38000, "Gitのコミット履歴中に誤ってハードコードされたパスワードやAPIキーを検知・阻止するCLI。"),
  c("trufflehog", "TruffleHog", "security", 85, 11.8, 33000, "リポジトリやS3バケット等の全体から有効なAPIキーや鍵の漏洩を高速探索するツール。"),
  c("cosign-sigstore", "Cosign (Sigstore)", "security", 80, 8.4, 21000, "コンテナイメージへの暗号署名と検証を行い、サプライチェーン攻撃を防ぐオープン標準。"),
  c("openfga", "OpenFGA", "security", 81, 14.5, 17000, "Auth0主導。Google Zanzibarスタイルの細かいアクセス制御（ReBAC）を構築するエンジン。"),
  c("casbin", "Casbin", "security", 76, 2.0, 42000, "ACL、RBAC、ABACなどの様々な認可モデルをマルチ言語で統一処理するアクセス制御基盤。"),
  c("keycloak", "Keycloak", "security", 82, 4.1, 110000, "Red Hat主導。OAuth 2.0、OIDC、SAMLに対応したオープンソースのシングルサインオン（SSO）BaaS。"),
  c("authelia", "Authelia", "security", 79, 6.5, 26000, "逆プロキシと連携し、2段階認証やSSOをシンプルな構成で提供するオープン認証サーバー。"),
  c("authentik", "authentik", "security", 85, 17.0, 29000, "Python/Goで構築された、モダンなUIと高い柔軟性を持つオープンソースID管理（IdP）。"),
  c("nmap-scanner", "Nmap", "security", 83, 1.2, 210000, "ネットワーク探査およびセキュリティ監査を行う世界最高レベルのポートスキャナー。"),
  c("metasploit", "Metasploit", "security", 78, -3.5, 140000, "ペネトレーションテストや概念実証（PoC）コードの検証に使用される侵入テストフレームワーク。"),
  c("snort-ids", "Snort", "security", 68, -8.0, 52000, "リアルタイムのパケット解析と攻撃検知を行う歴史あるオープンソースIDS/IPS。"),
  c("ossec-hids", "OSSEC", "security", 70, -4.0, 31000, "ログ分析、ファイル完全性監視、ルートキット検知を行うホスト型侵入検知システム。"),
  c("wazuh-platform", "Wazuh", "security", 86, 16.2, 48000, "XDR（拡張検知・対応）とSIEMを統合した、オープンソースのセキュリティモニタリング基盤。"),

  // ==================== Mobile Development (30個) ====================
  c("flutter-sdk", "Flutter", "mobile_dev", 88, 4.2, 280000, "Dartを用い、高パフォーマンスなモバイル・Web・デスクトップアプリをクロスプラットフォーム開発。"),
  c("react-native-sdk", "React Native", "mobile_dev", 78, -2.5, 210000, "Reactの知見でiOS/AndroidのネイティブUIを構築するMeta製標準フレームワーク。"),
  c("expo-framework", "Expo", "mobile_dev", 91, 19.8, 140000, "React Nativeアプリのビルド、通知、アップデート配信（EAS）を劇的に簡単化するフレームワーク。"),
  c("swiftui", "SwiftUI", "mobile_dev", 86, 8.5, 160000, "Apple公式。宣言的文法で美しいiOS/macOSアプリのUIを素早くデザインするフレームワーク。"),
  c("jetpack-compose", "Jetpack Compose", "mobile_dev", 87, 11.2, 150000, "Android公式。Kotlinによるモダンな宣言的UIツールキット。開発速度を飛躍させる。"),
  c("kotlin-multiplatform", "KMP (Kotlin Multiplatform)", "mobile_dev", 89, 23.0, 68000, "ロジックコードをiOSとAndroid間で完全共有しつつネイティブUIを維持する注目の本命技術。"),
  c("capacitor-mobile", "Capacitor", "mobile_dev", 76, 2.1, 38000, "Ionicチーム開発。Web資産（React/Vue/Svelte）をネイティブアプリ化するブリッジ。"),
  c("tauri-mobile", "Tauri Mobile", "mobile_dev", 84, 17.5, 29000, "Rustの安全性と極小フットプリントでモバイルアプリを構築するTauriのモバイル対応機能。"),
  c("xamarin-maui", ".NET MAUI", "mobile_dev", 62, -7.0, 72000, "C#/.NETを用いてiOS、Android、Windowsアプリを単一コードから出力するMicrosoft製基盤。"),
  c("ionic-framework", "Ionic", "mobile_dev", 60, -9.8, 95000, "Web標準技術（HTML/CSS/JS）で動作するクロスプラットフォームUIコンポーネント集。"),
  c("fastlane-mobile", "fastlane", "mobile_dev", 82, 1.5, 88000, "iOS/Androidアプリのスクショ作成、証明書管理、ストア配信自動化を行うCLIツール。"),
  c("cocoapods", "CocoaPods", "mobile_dev", 50, -14.0, 110000, "iOS開発の歴史的依存関係管理ツール。現在はSwift Package Managerへの移行が加速。"),
  c("swift-package-manager", "Swift Package Manager (SPM)", "mobile_dev", 85, 9.1, 92000, "Apple公式のSwift依存関係管理ツール。Xcodeに完全統合され軽量動作。"),
  c("gradle-build", "Gradle", "mobile_dev", 75, -2.0, 260000, "AndroidアプリおよびJVMプロジェクトの高速・柔軟なビルド自動化システム。"),
  c("detox-testing", "Detox", "mobile_dev", 74, 3.0, 21000, "React Nativeアプリ専用のグレーボックスE2Eテスト自動化フレームワーク。"),
  c("appium-testing", "Appium", "mobile_dev", 70, -4.5, 84000, "iOS/Androidのネイティブ・ハイブリッドアプリを自動化制御するクロスプラットフォームテスト。"),
  c("maestro-mobile", "Maestro", "mobile_dev", 88, 21.4, 25000, "YAMLで極めてシンプルかつ堅牢にiOS/AndroidアプリのUIテストを記述できる最先端E2E。"),
  c("realm-database", "Realm", "mobile_dev", 68, -5.0, 62000, "モバイルデバイス用に最適化された、SQLiteよりも高速で直感的なオブジェクトデータベース。"),
  c("watermelon-db", "WatermelonDB", "mobile_dev", 78, 6.0, 18000, "React Nativeアプリ向け。数万件のデータをミリ秒で処理するマルチスレッドSQLite DB。"),
  c("sqldelight", "SQLDelight", "mobile_dev", 83, 10.2, 24000, "SQL文から型安全なKotlin APIを自動生成し、KMP環境でも動作するデータベースライブラリ。"),
  c("firebase-crashlytics", "Firebase Crashlytics", "mobile_dev", 84, 2.8, 190000, "モバイルアプリのリアルタイムクラッシュレポートと詳細ログの解析を行う業界標準サービス。"),
  c("sentry-mobile", "Sentry Mobile", "mobile_dev", 86, 8.0, 130000, "アプリのエラー、スタックトレース、パフォーマンスモニタリングを統合管理するサービス。"),
  c("revenuecat", "RevenueCat", "mobile_dev", 90, 18.5, 41000, "アプリ内課金（In-App Purchase）やサブスクリプション実装の複雑さを一発で解決するBaaS。"),
  c("onesignal-push", "OneSignal", "mobile_dev", 78, -1.0, 95000, "プッシュ通知、アプリ内メッセージを無制限に近い規模で高速配信するエンゲージメントSaaS。"),
  c("flutterwave-pay", "Flutterwave", "mobile_dev", 72, 1.2, 19000, "グローバルな決済インフラをモバイルアプリに組み込むための支払いSDK。"),
  c("lottie-mobile", "Lottie", "mobile_dev", 82, 3.4, 88000, "After EffectsのアニメーションをJSONとしてレンダリングし、アプリでヌルサク動かす手法。"),
  c("rive-app", "Rive", "mobile_dev", 89, 20.1, 31000, "リアルタイムでインタラクティブに反応する軽量アニメーションをモバイル/Web用に構築。"),
  c("glamkit-mobile", "GLAMKit", "mobile_dev", 65, -3.0, 8000, "カメラ入力からのARフィルタやリアルタイム画像処理を支援するフレームワーク。"),
  c("unity-mobile", "Unity Engine", "mobile_dev", 85, 0.5, 410000, "モバイルゲームや3Dインタラクティブアプリ開発の世界的デファクトエンジン。"),
  c("unreal-mobile", "Unreal Engine 5", "mobile_dev", 88, 7.2, 290000, "実写級グラフィックとLumen/Nanite技術を備えたハイエンドゲーム＆モーショングラフィックス。"),

  // ==================== Data & AI Infrastructure (30個) ====================
  c("apache-spark", "Apache Spark", "data_ai", 80, -3.2, 320000, "大規模データ処理と分散コンピューティングのオープンソース業界標準エンジン。"),
  c("snowflake-db", "Snowflake", "data_ai", 86, 5.1, 210000, "ストレージと計算リソースを分離し、爆速でクエリを捌くクラウドデータウェハウス。"),
  c("databricks", "Databricks", "data_ai", 90, 14.5, 180000, "Sparkの創業者によるLakehouse基盤。データサイエンスとAIモデル開発を統合。"),
  c("bigquery", "Google BigQuery", "data_ai", 88, 6.2, 260000, "ペタバイト規模のデータを数秒でサーバーレスSQL解析するGoogle Cloudの基盤。"),
  c("dbt-labs", "dbt (data build tool)", "data_ai", 89, 12.8, 89000, "データウェアハウス内の変換（T）処理をSQLでソフトウェア開発のようにバージョン管理。"),
  c("apache-kafka", "Apache Kafka", "data_ai", 84, 1.5, 290000, "リアルタイムのストリーミングデータパイプラインを処理する分散イベントログ基盤。"),
  c("polars-py", "Polars", "data_ai", 93, 27.0, 95000, "Rust製でマルチスレッド並列動作する、Pandasより数十倍〜数百倍高速なデータ処理ライブラリ。"),
  c("pandas-py", "Pandas", "data_ai", 82, -4.0, 520000, "Pythonでのデータ解析、集計、加工になくてはならない歴史的データフレームライブラリ。"),
  c("duckdb-data", "DuckDB", "data_ai", 91, 22.4, 78000, "分析クエリに最適化され、ローカルファイルやPython環境とシームレスに結合するインメモリOLAP。"),
  c("apache-arrow", "Apache Arrow", "data_ai", 85, 8.1, 62000, "言語間でゼロコピーでインメモリデータを共有・高速転送するための列指向メモリエコシステム。"),
  c("ray-core", "Ray", "data_ai", 88, 16.2, 49000, "Python AIアプリケーションや大規模LLMの分散学習・推論をスケールさせる分散フレームワーク。"),
  c("vllm-inference", "vLLM", "data_ai", 94, 32.5, 68000, "PagedAttention技術により、LLMの推論サービング速度とスループットを数倍に引き上げるエンジン。"),
  c("tgi-huggingface", "TGI (Text Generation Inference)", "data_ai", 87, 11.0, 39000, "Hugging Faceによる、LLMの本番推論デプロイ用に最適化された高速サービングフレーム。"),
  c("triton-inference", "NVIDIA Triton", "data_ai", 85, 7.8, 41000, "GPU/CPU上で様々なAIモデル（PyTorch, TensorRT等）を統一サービングする推論サーバー。"),
  c("tensorrt-llm", "TensorRT-LLM", "data_ai", 91, 20.4, 45000, "NVIDIA GPUの性能を極限まで引き出してLLM推論を最高速化するコンパイルライブラリ。"),
  c("mlflow", "MLflow", "data_ai", 80, 2.1, 88000, "機械学習モデルの実験追跡、パラメータ管理、モデルレジストリを行うオープンソースMLOps。"),
  c("wandb-ai", "Weights & Biases", "data_ai", 88, 10.5, 76000, "AI・ディープラーニングの学習曲線、ハイパーパラメータ、メトリクスを視覚追跡するMLOps SaaS。"),
  c("dagster", "Dagster", "data_ai", 87, 17.8, 38000, "データアセット中心の設計で、パイプラインのテストと観察可能性（Observability）を高めるツール。"),
  c("apache-airflow", "Apache Airflow", "data_ai", 75, -5.8, 190000, "PythonコードでDAG（有向非巡回グラフ）を記述し、複雑なワークフローをスケジュール実行。"),
  c("prefect-io", "Prefect", "data_ai", 82, 6.0, 42000, "Pythonicにコードへデコレータを付けるだけで、モダンなデータパイプラインを構築・監視。"),
  c("pytorch", "PyTorch", "data_ai", 95, 9.2, 480000, "研究から産業界の本番運用まで、現代AIディープラーニング開発のデファクトフレームワーク。"),
  c("tensorflow", "TensorFlow", "data_ai", 65, -12.0, 390000, "Google製の機械学習ライブラリ。現在はPyTorchへの移行傾向が強いが巨大な実績。"),
  c("jax-google", "JAX", "data_ai", 84, 11.0, 58000, "AutogradとXLAコンパイルにより、高次元配列計算やAIモデル学習を爆速化するGoogleの基盤。"),
  c("onnx-runtime", "ONNX Runtime", "data_ai", 83, 4.5, 82000, "異なるフレームワークで作成されたAIモデルをクロスプラットフォームで高速実行する標準規格。"),
  c("trino-query", "Trino (PrestoSQL)", "data_ai", 82, 3.0, 65000, "複数のデータソース（S3, PostgreSQL等）へ単一のSQLで超高速分散クエリを発行するエンジン。"),
  c("apache-iceberg", "Apache Iceberg", "data_ai", 90, 21.0, 52000, "ペタバイト規模のデータレイク上でACIDトランザクションとタイムトラベルを実現するオープンテーブル規格。"),
  c("delta-lake", "Delta Lake", "data_ai", 84, 5.0, 71000, "Databricks主導。S3やGCSなどのオブジェクトストレージにACID保証をもたらすストレージ層。"),
  c("feast-feature-store", "Feast", "data_ai", 78, 4.2, 19000, "機械学習モデルの学習とリアルタイム推論で整合性のある特徴量を供給するオープン特徴量ストア。"),
  c("bentoml", "BentoML", "data_ai", 84, 8.9, 26000, "学習済みAIモデルを製品レベルの高性能なREST/gRPCマイクロサービスAPIへ迅速パッケージ化。"),
  c("label-studio", "Label Studio", "data_ai", 82, 6.4, 34000, "画像、テキスト、音声、動画などの学習データをチームでアノテーション・ラベル付けするオープンツール。"),

  // ==================== IoT & Embedded Systems (30個) ====================
  c("raspberry-pi-5", "Raspberry Pi 5", "iot_embedded", 92, 12.5, 240000, "PCIeスロットや高精度クロックを搭載し、ローカルAIも動く最高峰シングルボードコンピュータ。", true, "¥12,800", `https://www.amazon.co.jp/dp/B0D5BGV27R/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/61D19b-N7NL.jpg"),
  c("arduino-uno-r4", "Arduino Uno R4 WiFi", "iot_embedded", 88, 8.0, 150000, "ルネサス32ビットマイコンとESP32 Wi-Fi/Bluetoothモジュールを搭載した電子工作の標準ボード。", true, "¥4,800", `https://www.amazon.co.jp/dp/B0C8VTYW3X/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/61D19b-N7NL.jpg"),
  c("esp32-s3", "ESP32-S3", "iot_embedded", 91, 16.4, 110000, "ベクトル拡張命令を内蔵し、エッジでの音声認識や画像判定AIが安価に動く人気Wi-Fi/BTマイコン。", true, "¥1,850", `https://www.amazon.co.jp/dp/B0BS3L2JGM/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/61D19b-N7NL.jpg"),
  c("esp-idf", "ESP-IDF", "iot_embedded", 84, 7.2, 45000, "Espressif公式のC/C++開発フレームワーク。FreeRTOSを内蔵し本格的なIoT機器を構築。"),
  c("freertos", "FreeRTOS", "iot_embedded", 85, 2.5, 130000, "Amazon Web Servicesがサポートする、超軽量で信頼性の高い組み込み用リアルタイムOS。"),
  c("zephyr-rtos", "Zephyr RTOS", "iot_embedded", 89, 21.0, 39000, "Linux Foundationが推進する、高度なセキュリティとマルチアーキテクチャ対応を持つ次世代RTOS。"),
  c("embassy-rust", "Embassy (Rust Async)", "iot_embedded", 90, 25.8, 21000, "Rustのasync/await構文を用いて、極めて直感的かつ安全にマイコンの非同期処理を記述するフレームワーク。"),
  c("platformio", "PlatformIO", "iot_embedded", 87, 9.5, 78000, "VS Code上でマルチプラットフォーム（Arduino, ESP, STM32等）の組み込み開発を行う次世代IDE。"),
  c("stm32-cubemx", "STM32CubeMX", "iot_embedded", 78, -1.5, 89000, "STMicroelectronicsのマイコンピン配置やクロックツリーをGUIで直感設定しコード生成するツール。"),
  c("pico-w-rp2040", "Raspberry Pi Pico W", "iot_embedded", 86, 6.0, 120000, "独自マイコンRP2040にWi-Fiを追加した、数百円で購入できる高性能電子工作モジュール。", true, "¥1,200", `https://www.amazon.co.jp/dp/B0B579LNCT/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/61D19b-N7NL.jpg"),
  c("tinygo", "TinyGo", "iot_embedded", 82, 11.2, 28000, "Go言語の構文をそのまま使い、マイコンやWebAssembly向けに極小バイナリをコンパイルする環境。"),
  c("circuitpython", "CircuitPython", "iot_embedded", 76, 1.0, 42000, "Adafruitが主導する、教育や素早いプロトタイピングに最適な組み込みPython環境。"),
  c("mqtt-protocol", "MQTT (Mosquitto)", "iot_embedded", 82, 0.5, 160000, "帯域の狭いネットワークでも軽快にメッセージを送信できるIoT標準の軽量Pub/Subプロトコル。"),
  c("home-assistant", "Home Assistant", "iot_embedded", 93, 24.0, 180000, "自宅のあらゆるスマート家電や自作センサーをプライバシーを保って統合・自動化するオープン基盤。"),
  c("esphome", "ESPHome", "iot_embedded", 91, 22.1, 72000, "YAMLファイルを書くだけで、ESP8266/ESP32のカスタムセンサーを自動ビルドしてHome Assistantと連携。"),
  c("node-red", "Node-RED", "iot_embedded", 80, 2.0, 95000, "ノードをドラッグ＆ドロップで繋ぎ、IoTデバイスのデータフローやAPI連携を視覚的に構築するツール。"),
  c("ros-2-robotics", "ROS 2 (Robot OS)", "iot_embedded", 88, 14.2, 84000, "自動運転、ロボティクス、ドローン開発におけるオープンソースのミドルウェア標準。"),
  c("matter-protocol", "Matter Standard", "iot_embedded", 87, 18.0, 56000, "Apple, Google, Amazon等が策定した、メーカーの垣根を越えてスマートホーム機器が相互通信する規格。"),
  c("zigbee2mqtt", "Zigbee2MQTT", "iot_embedded", 85, 12.4, 48000, "各社のZigbeeスマートデバイス（センサー、電球等）のデータをMQTT経由で自由に制御するツール。"),
  c("ki-cad", "KiCad", "iot_embedded", 90, 15.0, 92000, "回路図作成からプリント基板（PCB）の3Dレイアウト設計までをこなす最高峰のオープンCAD。"),
  c("fritzing", "Fritzing", "iot_embedded", 68, -5.0, 51000, "ブレッドボード上の配線図を初心者にも直感的にわかりやすく作成できる電子工作デザイナー。"),
  c("saleae-logic", "Saleae Logic Analyzer", "iot_embedded", 84, 4.0, 31000, "SPIやI2C、UART通信のデジタル信号波形をPC上でキャプチャしてデバッグする必須ツール。"),
  c("openocd", "OpenOCD", "iot_embedded", 75, -2.0, 42000, "JTAG/SWDデバッガを介してマイコンのフラッシュ書込やステップ実行デバッグを行うオープンツール。"),
  c("segger-jlink", "SEGGER J-Link", "iot_embedded", 82, 1.8, 38000, "業界最高峰の書込速度と安定性を備えた、プロの組み込み開発でデファクト標準のJTAGデバッガ。"),
  c("edge-impulse", "Edge Impulse", "iot_embedded", 86, 16.5, 23000, "センサーやカメラのデータからマイコン上で動く超軽量TinyMLモデルを自動構築するプラットフォーム。"),
  c("tinyml-framework", "TensorFlow Lite for Micro", "iot_embedded", 78, 2.0, 39000, "わずか数十キロバイトのSRAMで機械学習モデルを実行する超小型推論エンジン。"),
  c("nrf-connect", "nRF Connect for Mobile", "iot_embedded", 80, 3.0, 62000, "Nordic Semiconductor製。Bluetooth Low Energy (BLE) デバイスの検出・キャラクタリスティック操作ツール。"),
  c("wireshark-ble", "Wireshark BLE Sniffer", "iot_embedded", 81, 2.5, 41000, "空気中を飛ぶBluetooth/Zigbeeパケットをドングルでキャプチャして解析するデバッグ手法。"),
  c("jetson-orin-nano", "NVIDIA Jetson Orin Nano", "iot_embedded", 89, 13.8, 65000, "40TOPSのAI性能を誇り、エッジロボットや自律走行システムで深層学習を実行するボード。"),
  c("modbus-protocol", "Modbus / CAN bus", "iot_embedded", 72, -4.0, 88000, "自動車や産業用PLC、工場自動化で長年使われている頑丈なシリアル通信プロトコル。"),

  // ==================== Productivity & Dev Tools (30個) ====================
  c("vs-code", "VS Code", "productivity", 82, 1.2, 620000, "世界を支配する万能エディタ。圧倒的な拡張機能エコシステムを持つ。"),
  c("eclipse", "Eclipse", "productivity", 35, -16.0, 90000, "かつてのJava開発標準。巨大なレガシープロジェクトで使われる。"),
  c("obsidian-notes", "Obsidian", "productivity", 85, 11.2, 104000, "思考をネットワーク化して保存できるローカルMarkdownファイル式の超高機能ナレッジベース。"),
  c("intellij-idea", "IntelliJ IDEA", "productivity", 70, -3.0, 202000, "JetBrains製。リファクタリング性能と補完に優れたプロ用最高峰Java総合環境。"),
  c("webstorm", "WebStorm", "productivity", 68, -4.1, 92000, "JS/TS開発に特化した、圧倒的にスマートなリファクタリングが可能な統合エディタ。"),
  c("neovim", "Neovim", "productivity", 84, 8.9, 113000, "Luaによる無限の拡張性を備えたVimの正統進化。キーボード駆動を貫く極根エディタ。"),
  c("emacs", "Emacs", "productivity", 45, -10.0, 53000, "Lispで拡張される環境そのもの。古参開発者に根強く愛される。"),
  c("1password", "1Password", "productivity", 88, 7.5, 184000, "SSH鍵やAPIトークンの管理、CLI連携が極めて強力なパスワード管理の金字塔。"),
  c("notion-app", "Notion", "productivity", 80, 2.0, 372000, "ドキュメント、タスク管理、データベースを集約するオールインワン情報共有。"),
  c("linear-app", "Linear", "productivity", 86, 12.0, 71000, "Jiraに代わる極めて軽快なUIとショートカット操作が魅力のアジャイルイシュートラッカー。"),
  c("jira-software", "Jira", "productivity", 40, -14.0, 270000, "企業向けプロジェクト管理の超定番。強力なカスタム性を持つ大企業の標準。"),
  c("xcode", "Xcode", "productivity", 65, -5.0, 82000, "Apple公式のiOS/macOS開発環境。SwiftUIのGUI設計とシミュレーターを内蔵。"),
  c("android-studio", "Android Studio", "productivity", 70, -2.1, 95000, "Google公式のAndroid開発環境。強力なエミュレータとレイアウトデザイナー。"),
  c("slack-app", "Slack", "productivity", 78, -1.0, 310000, "テック企業のコラボレーションチャットの事実上の標準。様々なAPIと統合。"),
  c("discord-app", "Discord", "productivity", 85, 4.2, 290000, "軽快な音声通話とコミュニティ機能。開発者の勉強会やOSS開発室として人気。"),
  c("zoom-meeting", "Zoom", "productivity", 60, -9.0, 180000, "遅延の少ないビデオ会議ツール。ペアプロやミーティングのインフラ。"),
  c("teams-microsoft", "Microsoft Teams", "productivity", 52, -12.0, 220000, "Officeエコシステムと結合した大企業向けの定番チャットツール。"),
  c("figma-design", "Figma", "productivity", 92, 6.0, 140000, "ブラウザ上で複数人同時にデザイン編集ができるWebデザイナー・開発者の標準。"),
  c("miro-board", "Miro", "productivity", 74, 1.0, 52000, "オンライン上の巨大なホワイトボード。ブレストやアーキテクチャ設計に最適。"),
  c("trello-board", "Trello", "productivity", 55, -10.5, 98000, "直感的なカンバン方式タスク管理ツール。小規模チームのToDo共有で活躍。"),
  c("asana-tasks", "Asana", "productivity", 64, -4.0, 43000, "プロジェクトのタスク依存関係をガントチャートやリストで追跡する管理ツール。"),
  c("monday-com", "monday.com", "productivity", 62, -6.0, 28000, "視覚的に優れたダッシュボードを作成し業務フローを追跡する管理ツール。"),
  c("clickup-tasks", "ClickUp", "productivity", 70, -1.5, 39000, "チャット、ドキュメント、タスクを一挙に統合したオールインワン業務管理。"),
  c("todoist", "Todoist", "productivity", 75, 2.0, 48000, "すっきりとしたUIでタスクをキーボード入力で爆速整理できるツール。"),
  c("craft-docs", "Craft", "productivity", 73, 1.2, 14000, "Mac/iOS環境に最適化された、美しいドキュメント作成が可能なエディタ。"),
  c("bear-notes", "Bear", "productivity", 68, -3.0, 12000, "Markdownに対応したMac/iOS用のスタイリッシュで高速なノートアプリ。"),
  c("logseq", "Logseq", "productivity", 75, 3.0, 23000, "プライバシーを保護するローカルMarkdownファイル式のアウトライン思考ツール。"),
  c("typora", "Typora", "productivity", 74, 0.5, 31000, "Markdown記述とリアルタイムプレビューを結合した超軽量エディタ。"),
  c("heptabase", "Heptabase", "productivity", 85, 14.0, 17000, "ホワイトボード上にノートをカード配置し視覚的に思考整理するツール。"),
  c("raycast-app", "Raycast Pro", "productivity", 90, 18.2, 42000, "AIチャットやクリップボード管理、カスタムスクリプトを内包したMac最強ランチャー。"),

  // ==================== Terminals & CLI (30個) ====================
  c("ghostty", "Ghostty", "terminals", 96, 38.5, 110000, "Zig言語で開発されたGPU加速対応の超高速ターミナル。極限の低遅延で席巻。"),
  c("zed", "Zed Editor", "terminals", 91, 24.1, 120000, "Rust製の爆速コードエディタ。VS Codeの重さに不満なユーザーに絶大な支持。"),
  c("raycast-launcher", "Raycast", "terminals", 90, 19.0, 83000, "Macの操作をキーボードだけで爆速化する拡張性の高いコマンドランチャー。"),
  c("warp-terminal", "Warp", "terminals", 80, 5.0, 62000, "Rust製で動作し、AIコマンド検索や入力のブロック単位編集に対応したターミナル。"),
  c("lazygit", "lazygit", "terminals", 86, 12.0, 38500, "ターミナル上でGit操作をすべてキーボード完結させるTUIの傑作ツール。"),
  c("alacritty", "Alacritty", "terminals", 74, -2.0, 44000, "Rustで書かれた、無駄のないGPU加速対応の超高速ターミナルエミュレータ。"),
  c("iterm2", "iTerm2", "terminals", 68, -6.0, 137000, "Macの標準ターミナルを置き換えてきた定番の高機能ターミナル。"),
  c("starship-prompt", "Starship", "terminals", 85, 10.0, 65000, "Rust製で動作し、あらゆるシェルに対応する超高速スタイリッシュプロンプト。"),
  c("zsh-shell", "Zsh", "terminals", 70, -3.0, 262000, "Macの標準シェルであり、高いカスタマイズ性と優れたプラグイン機能を持つ。"),
  c("fish-shell", "Fish", "terminals", 77, 4.0, 74000, "標準でシンタックスハイライト、自動補完が有効なユーザーフレンドリーなシェル。"),
  c("tmux", "tmux", "terminals", 72, -1.0, 62000, "単一のSSHセッション内で複数の仮想端末画面を分割・管理できるマルチプレクサ。"),
  c("git-fork", "Fork", "terminals", 78, 3.2, 28000, "爆速でグラフィカルにGit分岐を理解・マージ・競合解決できるGitクライアント。"),
  c("gitkraken", "GitKraken", "terminals", 70, -4.0, 83000, "美しいコミットグラフと直感的なマージ操作が魅力のデザイン重視Gitクライアント。"),
  c("postman-api", "Postman", "terminals", 75, -2.0, 24100, "APIの設計、テスト、実行、ドキュメント共有をチームで行えるプラットフォーム。"),
  c("kitty-terminal", "Kitty", "terminals", 80, 5.5, 39000, "GPUによる高速化、画像の表示、豊富なキーマップ設定に対応したターミナル。"),
  c("wezterm", "WezTerm", "terminals", 88, 16.0, 41000, "Rust製で動作し、Luaで高度な画面分割や外観カスタマイズを行えるターミナル。"),
  c("hyper-terminal", "Hyper", "terminals", 62, -9.0, 38000, "HTML/CSS/JSで開発された優れたテーマを持つElectron製ターミナル。"),
  c("windows-terminal", "Windows Terminal", "terminals", 80, 4.0, 89000, "Microsoft公式。タブ機能やGPUレンダリングを備えWSLを束ねるWindowsターミナル。"),
  c("oh-my-zsh", "Oh My Zsh", "terminals", 74, -3.5, 150000, "Zshシェルを強力にするための数千のプラグインやテーマを束ねた巨大基盤。"),
  c("powerlevel10k", "Powerlevel10k", "terminals", 82, 6.0, 68000, "Zsh用の超高速でグラフィカルなテーマプロンプト。"),
  c("bruno-api", "Bruno", "terminals", 89, 21.0, 21000, "Gitフレンドリーなマークアップ保存を採用し軽量かつ広告なしで動くPostman代替。"),
  c("insomnia-api", "Insomnia", "terminals", 73, -1.5, 53000, "GraphQLやgRPC、REST APIの送信・検証を綺麗なUIで行える定番クライアント。"),
  c("httpie", "HTTPie", "terminals", 75, 2.0, 31000, "curlよりも見やすくカラー表示やシンプルなJSON送信ができるCLIクライアント。"),
  c("curl-command", "curl", "terminals", 85, 1.0, 360000, "URL構文を用いてあらゆるサーバーデータを送受信する標準CLIコマンド。"),
  c("ripgrep", "ripgrep", "terminals", 88, 11.5, 59000, "Rust製の超高速ファイル内テキスト検索コマンド。grepの数十倍の速度。"),
  c("fzf-finder", "fzf", "terminals", 91, 14.0, 74000, "ターミナル上の履歴やファイル一覧をあいまい検索できる超軽量CLIフィルター。"),
  c("fd-find", "fd", "terminals", 84, 8.0, 38000, "findコマンドに代わる、Gitignore除外やカラー表示をサポートする爆速検索ツール。"),
  c("bat-cat", "bat", "terminals", 86, 9.5, 45000, "catコマンドに代わる、シンタックスハイライトやGit変更インジケータ表示ツール。"),
  c("htop-process", "htop", "terminals", 78, -2.0, 92000, "プロセスの稼働状況やメモリ消費を対話的に確認・終了できる定番TUIモニター。"),
  c("eza-ls", "eza", "terminals", 85, 10.2, 17000, "lsコマンドに代わる、アイコン表示やGitステータス表示に対応したRust製CLI。"),

  // ==================== Devices (30個) ====================
  c("keychron-q1-he", "Keychron Q1 HE", "devices", 93, 21.0, 36000, "磁気スイッチ搭載ラピッドトリガーキーボード。コトコトした打鍵感と高速反応が魅力。", true, "¥38,500", `https://www.amazon.co.jp/dp/B0CNGS1F9L/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/71P7u1F4yAL.jpg"),
  c("hhkb-studio", "HHKB Studio", "devices", 92, 18.0, 34000, "ポインターとジェスチャーパッドを統合したプロ向け静音メカニカルキーボード。", true, "¥44,000", `https://www.amazon.co.jp/dp/B0CKZ45MNN/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/61t47iP3aVL.jpg"),
  c("32-oled-4k-monitor", "32\" OLED 4K Monitor", "devices", 94, 25.4, 39000, "圧倒的な黒の表現力を持ち、低反射で目の疲労を和らげる32インチ有機ELディスプレイ。", true, "¥148,000", `https://www.amazon.co.jp/dp/B0CX1Z385Y/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/71z7wOsz8uL.jpg"),
  c("mx-master-3s", "Logicool MX Master 3S", "devices", 89, 6.2, 29000, "超高速電磁スクロールと静音クリックを備えたプレミアムエルゴノミクスマウス。", true, "¥16,900", `https://www.amazon.co.jp/dp/B0B3C4N316/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/61xfQ7m9xpL.jpg"),
  c("mx-ergo", "Logicool MX ERGO", "devices", 82, 2.0, 18000, "傾斜角を20度に調整でき、腕や手首の疲労を抑えるハイエンドトラックボール。", true, "¥15,400", `https://www.amazon.co.jp/dp/B075FRD74D/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/71p0Wf848vL.jpg"),
  c("hhkb-professional-hybrid", "HHKB Professional HYBRID Type-S", "devices", 88, 4.0, 27000, "静電容量無接点方式とミニマルなキー配列を誇る世界中で愛される名機。", true, "¥36,850", `https://www.amazon.co.jp/dp/B082TXWNX5/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/61R-aV3f9HL.jpg"),
  c("realforce-r3", "REALFORCE R3 キーボード", "devices", 84, 1.5, 22000, "東プレが誇る静電容量無接点方式。深さを個別に設定可能な信頼の日本製。", true, "¥34,980", `https://www.amazon.co.jp/dp/B09J4NGLL1/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/61X-uK2DVAL.jpg"),
  c("logitech-pebble-2", "Logicool Pebble M350", "devices", 68, -4.0, 26000, "静音・超薄型で携帯性に優れた持ち運びに最適なBluetoothミニマルマウス。", true, "¥3,200", `https://www.amazon.co.jp/dp/B0BZD51J1P/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/51w7r4K9mNL.jpg"),
  c("wooting-60he", "Wooting 60HE", "devices", 93, 20.0, 38000, "磁気スイッチと極小アナログ入力を持ちラピッドトリガーの先駆者となった60%キーボード。", true, "¥35,000", `https://www.amazon.co.jp/dp/B0BFPL17TF/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/61Nl-X3cM1L.jpg"),
  c("logitech-lift", "Logicool LIFT M800", "devices", 78, 3.0, 32000, "手の小さな方に最適な、手首をひねらず自然な角度で持てる57度縦型エルゴマウス。", true, "¥8,600", `https://www.amazon.co.jp/dp/B09V7N7R5K/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/61o28Nf3KBL.jpg"),
  c("kensington-slimblade-pro", "Kensington SlimBlade Pro", "devices", 76, 0.8, 12000, "55mm大径トラックボールをひねってスクロールするフラットトラックボール。", true, "¥16,800", `https://www.amazon.co.jp/dp/B0BM9L6KJS/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/61b7Uf85gEL.jpg"),
  c("sony-wh-1000xm5", "SONY WH-1000XM5", "devices", 80, 2.5, 92000, "業界最高峰ノイズキャンセリング。オフィス雑音を消去しコーディングに集中。", true, "¥42,000", `https://www.amazon.co.jp/dp/B0B136CWD7/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/51aBv7hF39L.jpg"),
  c("shure-mv7-microphone", "SHURE MV7 マイク", "devices", 78, 1.0, 44000, "リモート会議でクリアな声を届けるUSB/XLR接続対応のダイナミックマイク。", true, "¥32,800", `https://www.amazon.co.jp/dp/B08G7FGDS8/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/617h-OwsfXL.jpg"),
  c("eizo-coloredge-cs2740", "EIZO ColorEdge CS2740 4K", "devices", 83, 3.2, 15400, "正確な色表現とノングレアで目に優しい表示を提供するプロ向けモニター。", true, "¥198,000", `https://www.amazon.co.jp/dp/B0868J85W6/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/61D19b-N7NL.jpg"),
  c("apple-studio-display", "Apple Studio Display 27\"", "devices", 86, 6.0, 53000, "Macと直結可能な美しい5K解像度ディスプレイ。驚異的なテキスト視認性。", true, "¥219,800", `https://www.amazon.co.jp/dp/B09V7S1SPV/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/61mP87z0yOL.jpg"),
  c("elgato-wave3-microphone", "Elgato Wave:3", "devices", 76, 0.5, 32000, "音割れを防ぐクリップガード技術や直感ダイヤルを搭載したコンデンサーマイク。", true, "¥18,980", `https://www.amazon.co.jp/dp/B088KSCN2Z/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/617h-OwsfXL.jpg"),
  c("logicool-c920n-webcam", "Logicool C920n Webcam", "devices", 70, -4.5, 137000, "オンライン打ち合わせで美しい1080p映像を届ける定番カメラ。", true, "¥7,980", `https://www.amazon.co.jp/dp/B07RRC4BVF/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/718yG7e15AL.jpg"),
  c("nuphy-air75-v2", "NuPhy Air75 V2", "devices", 84, 11.0, 35000, "薄型ロープロファイルメカニカルキーボード。ポップなデザインで人気。", true, "¥21,800", `https://www.amazon.co.jp/dp/B0CLRP7L3X/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/71P7u1F4yAL.jpg"),
  c("logitech-pop-keys", "Logicool POP KEYS", "devices", 68, -5.0, 44000, "タイプライター風丸形キーに絵文字ボタンを搭載したポップなキーボード。", true, "¥11,000", `https://www.amazon.co.jp/dp/B09KGL132M/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/71P7u1F4yAL.jpg"),
  c("audio-technica-m50x", "Audio-Technica ATH-M50x", "devices", 88, 7.0, 65000, "世界中のレコーディング現場で使用されるプロ用モニターヘッドホン。", true, "¥19,800", `https://www.amazon.co.jp/dp/B00HVLUR86/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/51aBv7hF39L.jpg"),
  c("shure-sm7b", "Shure SM7B マイク", "devices", 92, 14.5, 54000, "配信者やミュージシャンに圧倒的支持を受けるダイナミックマイクの最高峰。", true, "¥58,000", `https://www.amazon.co.jp/dp/B0002E4Z8M/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/617h-OwsfXL.jpg"),
  c("focusrite-scarlett-2i2", "Focusrite Scarlett 2i2", "devices", 84, 4.0, 38000, "世界で最も売れているUSBオーディオインターフェイス。", true, "¥24,800", `https://www.amazon.co.jp/dp/B0CBPJMP24/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/51aBv7hF39L.jpg"),
  c("bose-qc-ultra-headphones", "Bose QC Ultra Headphones", "devices", 91, 16.0, 79000, "Bose最高峰のノイズキャンセリング。包み込むサウンドで集中力向上。", true, "¥52,800", `https://www.amazon.co.jp/dp/B0CFYNM289/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/51aBv7hF39L.jpg"),
  c("epos-h6pro-headset", "EPOS H6PRO ヘッドセット", "devices", 78, 1.2, 14000, "長時間装着しても疲れないクッションと音像定位に優れたヘッドセット。", true, "¥17,800", `https://www.amazon.co.jp/dp/B09F71B3P8/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/51aBv7hF39L.jpg"),
  c("steelseries-nova-pro", "SteelSeries Arctis Nova Pro", "devices", 89, 13.0, 41000, "ノイズキャンセリングと複数入力切替DACを搭載したハイエンドヘッドセット。", true, "¥48,000", `https://www.amazon.co.jp/dp/B0B147983W/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/51aBv7hF39L.jpg"),
  c("razer-deathadder-v3", "Razer DeathAdder V3 Pro", "devices", 92, 17.5, 59000, "超軽量63g。トッププロが信頼を寄せる握りやすいエルゴノミクスマウス。", true, "¥22,800", `https://www.amazon.co.jp/dp/B0B6Y7GHR2/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/61xfQ7m9xpL.jpg"),
  c("logitech-g-pro-x-superlight", "Logitech G PRO X 2", "devices", 93, 19.0, 84000, "超軽量設計と独自無線LIGHTSPEEDを搭載した定番ゲーミングマウス。", true, "¥24,800", `https://www.amazon.co.jp/dp/B0C3MBX4YL/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/61xfQ7m9xpL.jpg"),
  c("asus-rog-pg32ucdm", "ASUS ROG PG32UCDM 32\"", "devices", 94, 24.0, 21000, "第3世代新パネル有機EL搭載。リフレッシュレート240Hzの究極モニター。", true, "¥238,000", `https://www.amazon.co.jp/dp/B0D1G7Q34M/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/71z7wOsz8uL.jpg"),
  c("lg-ultrafine-5k-display", "LG UltraFine 5K 27MD5KL", "devices", 83, 2.0, 16000, "27インチ5K解像度を誇るMacBookファミリーと相性抜群のディスプレイ。", true, "¥144,800", `https://www.amazon.co.jp/dp/B07Y7NBFX8/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/718yG7e15AL.jpg"),
  c("benq-pd2700u-design", "BenQ PD2700U 27\" 4K", "devices", 81, 1.0, 29000, "正確な色表現と長時間の作業で目の疲れを和らげるアイケア搭載モニター。", true, "¥59,800", `https://www.amazon.co.jp/dp/B07F8TC29R/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/61D19b-N7NL.jpg"),

  // ==================== Gadgets & Office (30個) ====================
  c("benq-screenbar-halo", "BenQ ScreenBar Halo", "gadgets", 87, 8.5, 41000, "画面の反射をなくして手元だけを照らし目の負担を和らげるモニターライト。", true, "¥24,900", `https://www.amazon.co.jp/dp/B09KTDSNFX/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/61s86m521dL.jpg"),
  c("elgato-stream-deck-mk2", "Elgato Stream Deck MK.2", "gadgets", 89, 13.0, 53000, "15個のカスタム液晶キーを搭載。開発スクリプトやショートカットを1タップ実行。", true, "¥22,980", `https://www.amazon.co.jp/dp/B09738CV2G/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/61kM0Jv8uLL.jpg"),
  c("lg-dualup-monitor", "LG DualUp Monitor 28MQ780", "gadgets", 85, 6.2, 28000, "16:18のアスペクト比。縦に2枚並べたような変則ディスプレイ。コード閲覧に最高。", true, "¥79,800", `https://www.amazon.co.jp/dp/B0B5D982K5/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/718yG7e15AL.jpg"),
  c("dell-u4025qw-monitor", "DELL U4025QW 40\"", "gadgets", 90, 16.0, 32000, "40インチの5K2K曲面ウルトラワイドモニター。広大なワークスペース。", true, "¥248,000", `https://www.amazon.co.jp/dp/B0D5CSW1R4/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/81f9yR5wJML.jpg"),
  c("yubikey-5c-nfc", "YubiKey 5C NFC", "gadgets", 82, 3.0, 49000, "ハードウェアベースの二要素認証キー。Gitのコミット署名やセキュリティを強化。", true, "¥9,800", `https://www.amazon.co.jp/dp/B08FXC8T7N/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/51w7w0sY2DL.jpg"),
  c("caldigit-ts4-dock", "CalDigit TS4 Thunderbolt 4", "gadgets", 88, 11.2, 38000, "18個のポートを搭載し98W給電に対応したThunderbolt4ドックの最高峰。", true, "¥58,000", `https://www.amazon.co.jp/dp/B09PNP54L8/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/61b7Uf85gEL.jpg"),
  c("ergohuman-pro2", "Ergohuman PRO2", "gadgets", 91, 18.0, 24000, "独立式ランバーサポートを搭載し腰痛を軽減する最高峰エルゴノミクスチェア。", true, "¥151,800", `https://www.amazon.co.jp/dp/B0C3MBQ4M5/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/61b7Uf85gEL.jpg"),
  c("flexispot-e7-pro", "FlexiSpot E7 Pro", "gadgets", 92, 19.5, 62000, "ミリ単位で高さを調節でき、立ち座り作業を切り替える電動昇降デスク。", true, "¥61,600", `https://www.amazon.co.jp/dp/B09JGG2BND/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/61yXf5eD8IL.jpg"),
  c("yogi-bo-support", "Yogibo Support", "gadgets", 65, -6.0, 44000, "U字型クッション。膝上PC操作での腕や背中への負担を減らし快適化。", true, "¥15,000", `https://www.amazon.co.jp/dp/B07RZH4TLY/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/61b7Uf85gEL.jpg"),
  c("ravpower-100w-charger", "Anker Prime Wall Charger 100W", "gadgets", 88, 10.0, 65000, "GaN搭載。カードサイズでMacbook Proをフルスピード充電できる超小型充電器。", true, "¥9,990", `https://www.amazon.co.jp/dp/B0C3MC68Z1/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/51w7w0sY2DL.jpg"),
  c("anker-usb-c-hub-8in1", "Anker 555 USB-C Hub 8-in-1", "gadgets", 75, -2.0, 92000, "100W PD給電、4K HDMI、イーサネットポートを持つマルチハブ。", true, "¥7,990", `https://www.amazon.co.jp/dp/B093F56WXY/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/51w7w0sY2DL.jpg"),
  c("belkin-3in1-wireless-charger", "Belkin 3-in-1 充電器", "gadgets", 84, 5.0, 49000, "iPhone、Apple Watch、AirPodsを同時急速充電できるMagsafe公式充電器。", true, "¥22,000", `https://www.amazon.co.jp/dp/B09BN7J8GD/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/51w7w0sY2DL.jpg"),
  c("oura-ring-gen3", "Oura Ring Gen3", "gadgets", 80, 2.0, 38000, "睡眠スコアやストレスレベルを自動測定する超軽量ヘルススマートリング。", true, "¥49,800", `https://www.amazon.co.jp/dp/B09KGL132M/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/51w7w0sY2DL.jpg"),
  c("apple-watch-ultra-2", "Apple Watch Ultra 2", "gadgets", 91, 17.0, 120000, "堅牢チタニウムと大画面。GPS測位とバッテリ寿命に優れたスマートウォッチ。", true, "¥128,800", `https://www.amazon.co.jp/dp/B0CHXB8Z19/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/71P7u1F4yAL.jpg"),
  c("loftmat-wristrest", "Loftmat リストレスト", "gadgets", 68, -4.0, 12000, "手首の疲労を和らげる独自のフォームクッションパームレスト。", true, "¥4,800", `https://www.amazon.co.jp/dp/B082TXWNX5/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/61R-aV3f9HL.jpg"),
  c("deltahub-carpio-2", "Deltahub Carpio 2.0", "gadgets", 88, 12.5, 35000, "手のひらを支えて浮かせマウス操作時の腱鞘炎を予防する可動型リストレスト。", true, "¥4,980", `https://www.amazon.co.jp/dp/B08P54J2H5/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/61xfQ7m9xpL.jpg"),
  c("xiaomi-monitor-lightbar", "Xiaomi モニターライトバー", "gadgets", 76, 1.0, 22000, "非対称光学設計により画面に光を映し出さず手元だけを明るく照らすライト。", true, "¥6,980", `https://www.amazon.co.jp/dp/B08W3D944V/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/61s86m521dL.jpg"),
  c("loupedeck-live", "Loupedeck Live", "gadgets", 82, 3.0, 19000, "物理ノブとタッチ液晶で直感操作できるクリエイター向けコントローラー。", true, "¥37,900", `https://www.amazon.co.jp/dp/B08F7GD9W1/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/61kM0Jv8uLL.jpg"),
  c("stream-deck-pedal", "Elgato Stream Deck Pedal", "gadgets", 73, -1.0, 14000, "足元の3つのペダルでハンズフリー操作を実現するペダルスイッチ。", true, "¥12,980", `https://www.amazon.co.jp/dp/B09KLN3SXX/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/61kM0Jv8uLL.jpg"),
  c("herman-miller-aeron", "Herman Miller アーロンチェア", "gadgets", 94, 22.0, 68000, "オフィスの象徴。独自エルゴノミクス設計で腰への負荷を徹底軽減する極上チェア。", true, "¥262,000", `https://www.amazon.co.jp/dp/B072LXSBMB/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/61b7Uf85gEL.jpg"),
  c("okamura-contessa-2", "オカムラ コンテッサ セコンダ", "gadgets", 90, 15.0, 24000, "イタリアの巨匠がデザインした国産エルゴノミクスチェアの最高峰。", true, "¥214,000", `https://www.amazon.co.jp/dp/B073Z1T4G2/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/61b7Uf85gEL.jpg"),
  c("bauhutte-gaming-desk", "Bauhutte 昇降式ゲーミングデスク", "gadgets", 75, -2.0, 29000, "好みの高さに手動微調整可能な高剛性デスク。", true, "¥24,800", `https://www.amazon.co.jp/dp/B01M3P5P5T/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/61yXf5eD8IL.jpg"),
  c("flexispot-c7-chair", "FlexiSpot C7 オフィスチェア", "gadgets", 85, 9.0, 33000, "前傾チルト機能を搭載し前かがみ姿勢でも腰と背中をサポートするワークチェア。", true, "¥39,800", `https://www.amazon.co.jp/dp/B0CJFDZXL2/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/61b7Uf85gEL.jpg"),
  c("peakdesign-tech-pouch", "Peak Design テックポーチ", "gadgets", 88, 11.0, 48000, "折り紙式の間仕切りでケーブル類を小分け整理できる高機能ポーチ。", true, "¥9,900", `https://www.amazon.co.jp/dp/B07GLV285X/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/61b7Uf85gEL.jpg"),
  c("orbitkey-organizer", "Orbitkey キーオーガナイザー", "gadgets", 70, -3.0, 16000, "複数の鍵をスタックしてすっきりまとめる本革キーケース。", true, "¥5,500", `https://www.amazon.co.jp/dp/B01MDUFWSX/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/61b7Uf85gEL.jpg"),
  c("tile-pro-tracker", "Tile Pro 紛失防止タグ", "gadgets", 74, -1.0, 53000, "紛失をスマホのブザー音やGPS追跡で防ぐスマートトラッカー。", true, "¥5,400", `https://www.amazon.co.jp/dp/B09FYCGK98/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/51w7w0sY2DL.jpg"),
  c("apple-airtag", "Apple AirTag", "gadgets", 92, 19.0, 180000, "Appleの膨大な「探す」ネットワークを利用し正確に追跡するタグ。", true, "¥4,980", `https://www.amazon.co.jp/dp/B0935DYNPL/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/51w7w0sY2DL.jpg"),
  c("moft-laptop-stand", "MOFT 超薄型ノートPCスタンド", "gadgets", 84, 6.0, 82000, "PC背面に貼り付け一瞬でリフトアップして姿勢を正す極薄スタンド。", true, "¥3,280", `https://www.amazon.co.jp/dp/B07SR8CK6K/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/51w7w0sY2DL.jpg"),
  c("elgato-key-light", "Elgato Key Light", "gadgets", 80, 2.0, 26000, "PCから輝度や色温度をリモート制御。オンライン会議の表情を美しく照らす。", true, "¥28,980", `https://www.amazon.co.jp/dp/B07L755X9G/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/61s86m521dL.jpg"),
  c("ravpower-90w-charger", "RAVPower 90W PD充電器", "gadgets", 75, -2.5, 34000, "2ポート搭載。Macbook Proとスマホをフルスピード急速充電。", true, "¥5,980", `https://www.amazon.co.jp/dp/B082TXWNX5/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/51w7w0sY2DL.jpg"),

  // ==================== PC Components (30個) ====================
  c("intel-core-i9-14900k", "Intel Core i9-14900K", "components", 72, -5.2, 92000, "Intel第14世代最高峰CPU。24コア/32スレッドで重いコンパイル処理を一瞬で実行。", true, "¥98,000", `https://www.amazon.co.jp/dp/B0CGJDM3CH/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/61D19b-N7NL.jpg"),
  c("amd-ryzen-9-9950x", "AMD Ryzen 9 9950X", "components", 94, 23.5, 113000, "Zen5アーキテクチャのフラッグシップ。省電力性と最高峰のマルチスレッド開発力。", true, "¥112,000", `https://www.amazon.co.jp/dp/B0D8X21L1R/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/51wXpM41YRL.jpg"),
  c("rtx-4090", "NVIDIA GeForce RTX 4090", "components", 89, 8.4, 125000, "24GB VRAMを搭載しローカルAI（LLM・画像生成）のファインチューニングで大活躍。", true, "¥320,000", `https://www.amazon.co.jp/dp/B0BHDMTD6G/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/71i-41T5-zL.jpg"),
  c("rtx-5090", "NVIDIA GeForce RTX 5090", "components", 97, 36.2, 151000, "Blackwell世代最高峰GPU。AI演算性能が前世代の2倍となりローカルLLMの究極インフラ。", true, "¥380,000", `https://www.amazon.co.jp/dp/B0DJ2X385Z/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/71i-41T5-zL.jpg"),
  c("samsung-990-pro-2tb", "Samsung 990 PRO 2TB SSD", "components", 91, 14.0, 122000, "PCIe 4.0の限界に迫る読み込み最大7450MB/s。重いコンテナの起動を高速化。", true, "¥24,800", `https://www.amazon.co.jp/dp/B0BJDVFF47/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/71b2dZ0yEGL.jpg"),
  c("wd-black-sn850x-2tb", "WD_BLACK SN850X 2TB", "components", 88, 9.2, 92000, "超高速PCIe 4.0 M.2 SSD。高い信頼性と耐熱性でヘビーなビルドを支える。", true, "¥22,800", `https://www.amazon.co.jp/dp/B0B7CM227T/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/71b2dZ0yEGL.jpg"),
  c("corsair-ddr5-64gb", "Corsair DDR5 64GB", "components", 89, 11.0, 62000, "6000MHz。数十個のDockerコンテナ起動やAIエディタの同時立ち上げに必須。", true, "¥32,800", `https://www.amazon.co.jp/dp/B0B15DGZNH/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/71v1ZqYnUCL.jpg"),
  c("crucial-ddr5-32gb", "Crucial DDR5 32GB", "components", 80, 2.0, 83000, "安定性と信頼性を誇るメモリの老舗。エラーの出ない定評のある動作。", true, "¥16,800", `https://www.amazon.co.jp/dp/B09HW18CSB/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/71v1ZqYnUCL.jpg"),
  c("asus-rog-strix-x670e", "ASUS ROG STRIX X670E-F", "components", 85, 7.5, 44000, "AMD Ryzen 9000番台対応。電源回路と排熱性能に優れたマザーボード。", true, "¥58,000", `https://www.amazon.co.jp/dp/B0BF5F9F42/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/718yG7e15AL.jpg"),
  c("noctua-nh-d15-gen2", "Noctua NH-D15 G2", "components", 92, 19.0, 53000, "空冷CPUクーラーの王者。簡易水冷を凌駕する静音性と冷やしきる冷却力。", true, "¥21,800", `https://www.amazon.co.jp/dp/B0D6F1D385/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/71h3K7yVULL.jpg"),
  c("nzxt-kraken-elite-360", "NZXT KRAKEN Elite 360", "components", 90, 15.0, 43000, "高精細液晶画面を水冷ヘッドに搭載。CPU温度を美しくモニタリング。", true, "¥41,800", `https://www.amazon.co.jp/dp/B0BYMX8K7G/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/71h3K7yVULL.jpg"),
  c("corsair-rm1000x-power", "Corsair RM1000x 1000W", "components", 84, 4.0, 65000, "80PLUS GOLD認定。高消費電力グラボを安定稼働させる電源ユニット。", true, "¥24,800", `https://www.amazon.co.jp/dp/B08ZKPMNKK/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/51w7w0sY2DL.jpg"),
  c("fractal-design-north", "Fractal Design North", "components", 93, 21.4, 59000, "天然木材をフロントパネルに採用したインテリアに調和するPCケース。", true, "¥26,800", `https://www.amazon.co.jp/dp/B0BPLJ5X1T/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/71j1Z4y8uLL.jpg"),
  c("rtx-4070-ts", "GeForce RTX 4070 Ti SUPER", "components", 87, 9.8, 86000, "16GB VRAM搭載。低発熱で十分なローカルAI・ディープラーニング向けグラボ。", true, "¥134,800", `https://www.amazon.co.jp/dp/B0CS3V59C6/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/71i-41T5-zL.jpg"),
  c("ryzen-7-7800x3d", "AMD Ryzen 7 7800X3D", "components", 85, 6.0, 92000, "3D V-Cache搭載。メモリレイテンシ低減によりビルド処理でも強力。", true, "¥54,800", `https://www.amazon.co.jp/dp/B0BXM1C4Z2/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/51wXpM41YRL.jpg"),
  c("crucial-t700-1tb", "Crucial T700 1TB Gen5 SSD", "components", 86, 8.0, 32000, "PCIe 5.0規格。読み込み最大12400MB/sという圧倒的速度を誇るSSD。", true, "¥29,800", `https://www.amazon.co.jp/dp/B0C3K9MCFR/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/71b2dZ0yEGL.jpg"),
  c("intel-core-i7-14700k", "Intel Core i7-14700K", "components", 68, -6.0, 137000, "20コア/28スレッドのハイスペック。実用的なプロ開発者向けCPU。", true, "¥62,800", `https://www.amazon.co.jp/dp/B0CGJDJMJD/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/61D19b-N7NL.jpg"),
  c("corsair-vengeance-ddr4-32", "Corsair DDR4 32GB", "components", 50, -14.0, 92000, "DDR4世代の安定メモリ。多くの開発機で動作し続けている定番。", true, "¥9,800", `https://www.amazon.co.jp/dp/B0143UM4TC/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/71v1ZqYnUCL.jpg"),
  c("thermalright-peerless-120", "Thermalright Peerless Assassin", "components", 78, 3.0, 44000, "安価でありながら水冷並みの冷却効率を実現した高コスパ空冷クーラー。", true, "¥5,200", `https://www.amazon.co.jp/dp/B09S394S99/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/71h3K7yVULL.jpg"),
  c("asus-tuf-gaming-b760", "ASUS TUF GAMING B760-PLUS", "components", 70, -3.0, 65000, "Intel LGA1700対応。ミリタリー規格の耐久性を備えた定番マザーボード。", true, "¥23,000", `https://www.amazon.co.jp/dp/B0BPY9J5F1/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/718yG7e15AL.jpg"),
  c("seasonic-focus-850w", "Seasonic FOCUS GX-850", "components", 81, 4.0, 28000, "電源の老舗Seasonic製。長寿命設計によりプロの自作機で絶大な信頼。", true, "¥21,800", `https://www.amazon.co.jp/dp/B0BTMDD3B1/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/51w7w0sY2DL.jpg"),
  c("samsung-870-evo-2tb", "Samsung 870 EVO 2TB", "components", 62, -8.0, 158000, "2.5インチSATA接続の定番SSD。データ倉庫用途で手堅いロングセラー。", true, "¥18,900", `https://www.amazon.co.jp/dp/B08QJD5C2Q/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/71b2dZ0yEGL.jpg"),
  c("msi-mag-b650-tomahawk", "MSI MAG B650 TOMAHAWK", "components", 74, 2.0, 35000, "AMD B650。拡張性と熱効率を両立したAM5自作の定番マザーボード。", true, "¥28,900", `https://www.amazon.co.jp/dp/B0BDS8TC1G/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/718yG7e15AL.jpg"),
  c("lian-li-uni-fan-sl120", "Lian Li UNI FAN SL120", "components", 75, 1.5, 32000, "配線を大幅削減するモジュール式連結ケースファン。美しいライティング。", true, "¥12,800", `https://www.amazon.co.jp/dp/B0D2X58QML/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/71i-41T5-zL.jpg"),
  c("noctua-nf-a12x25", "Noctua NF-A12x25 PWM", "components", 87, 9.0, 38000, "究極の静音と高静圧を誇るケースファンの最高峰。ほぼ無音で冷却。", true, "¥4,600", `https://www.amazon.co.jp/dp/B07C5VG64V/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/71h3K7yVULL.jpg"),
  c("creative-pebble-v3", "Creative Pebble V3", "cat", 72, 0.5, 62000, "球体デザインから豊かで高音質なサウンドを出力するデスクトップ用スピーカー。", true, "¥5,980", `https://www.amazon.co.jp/dp/B08F596V9X/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/51aBv7hF39L.jpg"),
  c("wd-blue-4tb-hdd", "WD Blue 4TB HDD", "components", 35, -15.0, 92000, "バックアップやログアーカイブなど大容量保管で定番のハードディスク。", true, "¥10,800", `https://www.amazon.co.jp/dp/B08VH8C3WZ/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/71b2dZ0yEGL.jpg"),
  c("gskill-trident-z5-rgb", "G.Skill Trident Z5 RGB", "components", 83, 5.0, 41000, "OC性能と美しいRGBライティングを搭載したハイエンドPC用メモリ。", true, "¥23,800", `https://www.amazon.co.jp/dp/B09P1M51M8/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/71v1ZqYnUCL.jpg"),
  c("silverstone-sfx-700w", "SilverStone 700W SFX電源", "components", 68, -2.0, 28000, "小型PCケース（Mini-ITX）で大容量電力を供給するためのSFX電源。", true, "¥18,900", `https://www.amazon.co.jp/dp/B08MZHN7J8/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/51w7w0sY2DL.jpg"),
  c("deepcool-ak400", "Deepcool AK400", "components", 80, 4.0, 65000, "抜群の静音性とミドルクラスCPUを冷やす新定番空冷CPUクーラー。", true, "¥3,800", `https://www.amazon.co.jp/dp/B09VLF4C8V/?tag=${tag}`, "https://images-fe.ssl-images-amazon.com/images/I/71h3K7yVULL.jpg")
];
